In [1]:
#manipulate dataframes in python
import pandas as pd
import numpy as np

#make API calls with python
import requests

#allows us to store results of API call cleanly
import json

import math
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
api_key = "a45a33bca80b5e1907adc4587be5c346b897dda7"

# Reason for choosing ACS1
The current main task is getting detailed population estimates for cities in the NYU City Health Dataset, which is the top 510 cities in the U.S. Therefore, ACS1 contains data for areas with populations of 65,000+. ACS1 will cover most cities in the NYU City Health Dataset. 

# Data check up

We want to get stable data variables throughout the years, so we can rely on the data that we pull out using API. <br>
The following will be checked first.<br>
1. Do 2010-2018 ACS have same cities -using FIPS CODE
2. Stable variable for different years -  Variables and/or variable names can be changed and it can give us different metrics (for example, one year is the whole number and one year is a percentage). We want to find the most stable variables for each category, so we can use the same metrics in the final data products. The variable test will be checked on each category. 

## 1. Do 2010-2018 ACS have same cities

We want to know ACS 1 year estimates of each year have the same cities. In the initial API pulls 2018, ACS1, which contains data for areas with populations of 65,000+, has 630 cities.  <br>

I will use two API data from Census 
1. ACS1 (Sex, Race, Ethnicity)
2. ACS1/subject (Age group)
<br>



ACS1 also has age, but ACS1/subject has age group. For example, ACS1 age is 1 or 5 years age groups, but the ACS1/subject age group is 15 to 44 and under 18. <br>So, we can minimize the calculation variables.

For checking number of cities in each dataset, I will check both dataset with total population and sex because these variables are present in both dataset and also variables in almost all cities, if the city has ACS dataset.

In [3]:
# For 

dic = {}
for year in range(2010,2019):
    
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,S0101_C01_001E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}/{sub}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    
    dic[year] = data
    
    

2010 556
2011 563
2012 569
2013 583
2014 592
2015 597
2016 606
2017 615
2018 631


In [4]:
cols= ['NAME', 'Pop_Total', 'fips_state', 'fips_place']

In [5]:
for year in range(2010,2019):
    print('cities_{} = pd.DataFrame(dic[{}][1:], columns=cols)'.format(year,year))

cities_2010 = pd.DataFrame(dic[2010][1:], columns=cols)
cities_2011 = pd.DataFrame(dic[2011][1:], columns=cols)
cities_2012 = pd.DataFrame(dic[2012][1:], columns=cols)
cities_2013 = pd.DataFrame(dic[2013][1:], columns=cols)
cities_2014 = pd.DataFrame(dic[2014][1:], columns=cols)
cities_2015 = pd.DataFrame(dic[2015][1:], columns=cols)
cities_2016 = pd.DataFrame(dic[2016][1:], columns=cols)
cities_2017 = pd.DataFrame(dic[2017][1:], columns=cols)
cities_2018 = pd.DataFrame(dic[2018][1:], columns=cols)


In [6]:
for year in range(2010,2019):
    df_name = ('cities_{} = pd.DataFrame(dic[{}][1:], columns=cols)'.format(year,year))
    exec(df_name)

In [7]:
df_name

'cities_2018 = pd.DataFrame(dic[2018][1:], columns=cols)'

In [8]:
cities_2010

NAME Pop_Total fips_state  \
0                             Birmingham city, Alabama    211670         01   
1                                 Dothan city, Alabama     66121         01   
2                                 Hoover city, Alabama     80376         01   
3                             Huntsville city, Alabama    181126         01   
4                                 Mobile city, Alabama    195249         01   
5                             Montgomery city, Alabama    206655         01   
6                             Tuscaloosa city, Alabama     90637         01   
7                       Anchorage municipality, Alaska    293227         02   
8                               Avondale city, Arizona     76446         04   
9                               Chandler city, Arizona    236775         04   
10                             Flagstaff city, Arizona     65976         04   
11                               Gilbert town, Arizona    209007         04   
12                              Glendale city, Arizona    227358         04   
13                              Goodyear city, Arizona     65445         04   
14                                  Mesa city, Arizona    440248         04   
15                                Peoria city, Arizona    154475         04   
16                               Phoenix city, Arizona   1449481         04   
17                         San Tan Valley CDP, Arizona     74977         04   
18                            Scottsdale city, Arizona    217977         04   
19                              Surprise city, Arizona    117826         04   
20                                 Tempe city, Arizona    162123         04   
21                                Tucson city, Arizona    521132         04   
22                                  Yuma city, Arizona     93409         04   
23                         Fayetteville city, Arkansas     73946         05   
24                           Fort Smith city, Arkansas     86338         05   
25                            Jonesboro city, Arkansas     67486         05   
26                          Little Rock city, Arkansas    193973         05   
27                           Springdale city, Arkansas     70751         05   
28                            Alameda city, California     73981         06   
29                           Alhambra city, California     83202         06   
30                            Anaheim city, California    337259         06   
31                            Antioch city, California    102745         06   
32                       Apple Valley town, California     69387         06   
33                        Arden-Arcade CDP, California     87272         06   
34                        Bakersfield city, California    348582         06   
35                       Baldwin Park city, California     75496         06   
36                         Bellflower city, California     76717         06   
37                           Berkeley city, California    112824         06   
38                         Buena Park city, California     80766         06   
39                            Burbank city, California    103472         06   
40                          Camarillo city, California     65406         06   
41                           Carlsbad city, California    105707         06   
42                             Carson city, California     91828         06   
43                              Chico city, California     86213         06   
44                              Chino city, California     78237         06   
45                        Chino Hills city, California     75070         06   
46                        Chula Vista city, California    244789         06   
47                     Citrus Heights city, California     83490         06   
48                             Clovis city, California     95915         06   
49                            Compton city, California     96558         06   
50                   

In [9]:
# Set up each year's dataset

cities_2010 = pd.DataFrame(dic[2010][1:], columns=cols)
cities_2010["Year"]=2010


cities_2011 = pd.DataFrame(dic[2011][1:], columns=cols)
cities_2011["Year"]=2011


cities_2012 = pd.DataFrame(dic[2012][1:], columns=cols)
cities_2012["Year"]=2012

cities_2013 = pd.DataFrame(dic[2013][1:], columns=cols)
cities_2013["Year"]=2013


cities_2014 = pd.DataFrame(dic[2014][1:], columns=cols)
cities_2014["Year"]=2014


cities_2015 = pd.DataFrame(dic[2015][1:], columns=cols)
cities_2015["Year"]=2015

cities_2016 = pd.DataFrame(dic[2016][1:], columns=cols)
cities_2016["Year"]=2016

cities_2017 = pd.DataFrame(dic[2017][1:], columns=cols)
cities_2017["Year"]=2017

cities_2018 = pd.DataFrame(dic[2018][1:], columns=cols)
cities_2018["Year"]=2018

In [10]:
cities_2010.head()

NAME Pop_Total fips_state fips_place  Year
0  Birmingham city, Alabama    211670         01      07000  2010
1      Dothan city, Alabama     66121         01      21184  2010
2      Hoover city, Alabama     80376         01      35896  2010
3  Huntsville city, Alabama    181126         01      37000  2010
4      Mobile city, Alabama    195249         01      50000  2010

In [11]:
cities_in_2010 = cities_2010['NAME'].to_list()

In [12]:
# Check 2011

cities_2011[~cities_2011['NAME'].isin(cities_in_2010)]

NAME Pop_Total fips_state fips_place  Year
44         Glen Burnie CDP, Maryland     69026         24      32650  2011
313        Casas Adobes CDP, Arizona     67496         04      10670  2011
367  Florence-Graham CDP, California     68626         06      24477  2011
408       Palo Alto city, California     65419         06      55282  2011
414  Rancho Cordova city, California     65614         06      59444  2011
459    Walnut Creek city, California     65232         06      83346  2011
464       Yuba City city, California     65041         06      86972  2011

In [13]:
# Check 2012

cities_2012[~cities_2012['NAME'].isin(cities_in_2010)]

NAME Pop_Total fips_state fips_place  \
1              Palo Alto city, California     66359         06      55282   
7         Rancho Cordova city, California     66999         06      59444   
37   South San Francisco city, California     65565         06      73262   
53          Walnut Creek city, California     65696         06      83346   
58             Yuba City city, California     65105         06      86972   
114               Pine Hills CDP, Florida     69219         12      56825   
216              Franklin city, Tennessee     66278         47      27740   
276                   Millcreek CDP, Utah     66939         49      50150   
306                Pasco city, Washington     64029         53      53545   
395             Glen Burnie CDP, Maryland     70285         24      32650   
471             Casas Adobes CDP, Arizona     71976         04      10670   
525       Florence-Graham CDP, California     63284         06      24477   
541        Jurupa Valley city, California     97419         06      37692   

     Year  
1    2012  
7    2012  
37   2012  
53   2012  
58   2012  
114  2012  
216  2012  
276  2012  
306  2012  
395  2012  
471  2012  
525  2012  
541  2012

In [14]:
# Check 2013

cities_2013[~cities_2013['NAME'].isin(cities_in_2010)]

NAME Pop_Total fips_state fips_place  \
33           Bossier City city, Louisiana     66334         22      08920   
42                 Bethesda CDP, Maryland     66364         24      07125   
46            Gaithersburg city, Maryland     65689         24      31175   
48              Glen Burnie CDP, Maryland     66760         24      32650   
84                  Eagan city, Minnesota     65453         27      17288   
85            Maple Grove city, Minnesota     65406         27      40166   
91               Woodbury city, Minnesota     65659         27      71428   
118              Bayonne city, New Jersey     65024         34      03580   
158           Bismarck city, North Dakota     66063         38      07200   
204              Franklin city, Tennessee     68872         47      27740   
206          Johnson City city, Tennessee     65796         47      38320   
221             Kirkland city, Washington     84434         53      35940   
222                Pasco city, Washington     70345         53      53545   
295                  Victoria city, Texas     65097         48      75428   
327             Casas Adobes CDP, Arizona     69653         04      10670   
346      North Little Rock city, Arkansas     66086         05      50450   
362            Carmichael CDP, California     66747         06      11390   
398        Jurupa Valley city, California     98036         06      37692   
424            Palo Alto city, California     66638         06      55282   
430       Rancho Cordova city, California     67919         06      59444   
444         San Clemente city, California     65021         06      65084   
461  South San Francisco city, California     66174         06      73262   
462        South Whittier CDP, California     65365         06      73430   
478         Walnut Creek city, California     66890         06      83346   
483            Yuba City city, California     65410         06      86972   
526               Kissimmee city, Florida     65186         12      36950   
540               Pine Hills CDP, Florida     67295         12      56825   

     Year  
33   2013  
42   2013  
46   2013  
48   2013  
84   2013  
85   2013  
91   2013  
118  2013  
158  2013  
204  2013  
206  2013  
221  2013  
222  2013  
295  2013  
327  2013  
346  2013  
362  2013  
398  2013  
424  2013  
430  2013  
444  2013  
461  2013  
462  2013  
478  2013  
483  2013  
526  2013  
540  2013

In [15]:
# Check 2015

cities_2015[~cities_2015['NAME'].isin(cities_in_2010)]

NAME   Pop_Total fips_state fips_place  \
9               Casas Adobes CDP, Arizona       65265         04      10670   
28       North Little Rock city, Arkansas       66506         05      50450   
44             Carmichael CDP, California       63215         06      11390   
65        Florence-Graham CDP, California       66359         06      24477   
81         Jurupa Valley city, California      100314         06      37692   
82         Laguna Niguel city, California       65812         06      39248   
108            Palo Alto city, California       66848         06      55282   
114       Rancho Cordova city, California       71026         06      59444   
125               Brentwood CDP, New York       63792         36      08026   
149           Bismarck city, North Dakota       70240         38      07200   
195              Franklin city, Tennessee       72635         47      27740   
197          Johnson City city, Tennessee       65369         47      38320   
213                Cedar Park city, Texas       64837         48      13552   
215                    Conroe city, Texas       68592         48      16432   
241             New Braunfels city, Texas       69923         48      50820   
256                  Victoria city, Texas       67581         48      75428   
266               South Jordan city, Utah       66639         49      70850   
290             Kirkland city, Washington       87267         53      35940   
291           Marysville city, Washington       66773         53      43955   
292                Pasco city, Washington       68097         53      53545   
322         San Clemente city, California       65532         06      65084   
339  South San Francisco city, California       67271         06      73262   
355         Walnut Creek city, California       68906         06      83346   
360            Yuba City city, California       66944         06      86972   
364             Broomfield city, Colorado       65065         08      09280   
396            Delray Beach city, Florida       66261         12      17100   
403               Homestead city, Florida       66500         12      32275   
406               Kissimmee city, Florida       69152         12      36950   
420               Pine Hills CDP, Florida       76081         12      56825   
422                Poinciana CDP, Florida       73943         12      57900   
431             The Villages CDP, Florida  -999999999         12      71625   
441            Macon-Bibb County, Georgia      153459         13      49008   
480                       Ames city, Iowa       65052         19      01855   
491                  Shawnee city, Kansas       65058         20      64500   
497          Bossier City city, Louisiana       68097         22      08920   
509           Gaithersburg city, Maryland       67445         24      31175   
511             Glen Burnie CDP, Maryland       69859         24      32650   
512              Rockville city, Maryland       66998         24      67675   
548                 Eagan city, Minnesota       66288         27      17288   
549           Maple Grove city, Minnesota       68381         27      40166   
555              Woodbury city, Minnesota       67850         27      71428   
582              Bayonne city, New Jersey       66303         34      03580   

     Year  
9    2015  
28   2015  
44   2015  
65   2015  
81   2015  
82   2015  
108  2015  
114  2015  
125  2015  
149  2015  
195  2015  
197  2015  
213  2015  
215  2015  
241  2015  
256  2015  
266  2015  
290  2015  
291  2015  
292  2015  
322  2015  
339  2015  
355  2015  
360  2015  
364  2015  
396  2015  
403  2015  
406  2015  
420  2015  
422  2015  
431  2015  
441  2015  
480  2015  
491  2015  
497  2015  
509  2015  
511  2015  
512  2015  
548  2015  
549  2015  
555  2015  
582  2015

In [16]:
# Check 2018
cities_2018[~cities_2018['NAME'].isin(cities_in_2010)]

NAME   Pop_Total fips_state fips_place  \
12               Palm Harbor CDP, Florida       65994         12      54350   
13               Alpharetta city, Georgia       66263         13      01696   
24                     Conroe city, Texas       87656         48      16432   
25            Marysville city, Washington       69765         53      43955   
32             Delray Beach city, Florida       69356         12      17100   
37               Woodbury city, Minnesota       71299         27      71428   
38               Bayonne city, New Jersey       65082         34      03580   
45              New Braunfels city, Texas       85566         48      50820   
46                South Jordan city, Utah       74155         49      70850   
48                   Auburn city, Alabama       65737         01      03076   
53        Florence-Graham CDP, California       63621         06      24477   
60                        Ames city, Iowa       67155         19      01855   
62              Glen Burnie CDP, Maryland       65987         24      32650   
63              Lakeville city, Minnesota       65871         27      35180   
91              Casas Adobes CDP, Arizona       75694         04      10670   
115        South Whittier CDP, California       65577         06      73430   
126                Georgetown city, Texas       74176         48      29336   
131         Castro Valley CDP, California       63226         06      11964   
133                     Ankeny city, Iowa       65282         19      02305   
143            West Des Moines city, Iowa       67127         19      83910   
152                  Victoria city, Texas       67020         48      75428   
163               Homestead city, Florida       70469         12      32275   
165                  Shawnee city, Kansas       65844         20      64500   
181        Framingham city, Massachusetts       73123         25      24960   
186                       Lehi city, Utah       66029         49      44320   
190                 Conway city, Arkansas       66421         05      15190   
197         Walnut Creek city, California       69814         06      83346   
203               Kissimmee city, Florida       73596         12      36950   
204                Poinciana CDP, Florida       71331         12      57900   
212      North Little Rock city, Arkansas       66126         05      50450   
217             Broomfield city, Colorado       69267         08      09280   
239  South San Francisco city, California       67736         06      73262   
244           Maple Grove city, Minnesota       71812         27      40166   
249              Franklin city, Tennessee       80920         47      27740   
269        Jurupa Valley city, California      108400         06      37692   
273             The Hammocks CDP, Florida       64910         12      71569   
282            Sammamish city, Washington       65726         53      61115   
289            Yuba City city, California       66988         06      86972   
298               Brentwood CDP, New York       64855         36      08026   
316            South Fulton city, Georgia       97266         13      72122   
320          Bossier City city, Louisiana       68222         22      08920   
325           Bismarck city, North Dakota       71843         38      07200   
335               Madera city, California       65711         06      45022   
339                 Jupiter town, Florida       65544         12      35875   
341            Macon-Bibb County, Georgia      153095         13      49008   
352                 Lodi city, California       66995         06      42202   
370             Kirkland city, Washington       89557         53      35940   
377           Wellington village, Florida       65190         12      75812   
390                 Rogers city, Arkansas       67615         05      60410   
393        Lake Elsinore city, California       68187         06      39486   
394     

In [17]:
# Check 2018 with 2017

cities_2018[~cities_2018['NAME'].isin(cities_2017['NAME'])]

NAME Pop_Total fips_state fips_place  Year
12         Palm Harbor CDP, Florida     65994         12      54350  2018
48             Auburn city, Alabama     65737         01      03076  2018
63        Lakeville city, Minnesota     65871         27      35180  2018
115  South Whittier CDP, California     65577         06      73430  2018
133               Ankeny city, Iowa     65282         19      02305  2018
143      West Des Moines city, Iowa     67127         19      83910  2018
181  Framingham city, Massachusetts     73123         25      24960  2018
186                 Lehi city, Utah     66029         49      44320  2018
282      Sammamish city, Washington     65726         53      61115  2018
316      South Fulton city, Georgia     97266         13      72122  2018
339           Jupiter town, Florida     65544         12      35875  2018
377     Wellington village, Florida     65190         12      75812  2018
394        Rocklin city, California     67231         06      62364  2018
499             Rowlett city, Texas     66686         48      63572  2018
502          Blaine city, Minnesota     65215         27      06382  2018
511       Noblesville city, Indiana     66358         18      54180  2018
535      Wesley Chapel CDP, Florida     65249         12      75875  2018
581        Redmond city, Washington     67680         53      57535  2018

In [18]:
# Check ACS1 API


dic = {}
for year in range(2010,2019):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,B01001_001E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic[year] = data
    
    

2010 556
2011 563
2012 569
2013 583
2014 592
2015 597
2016 606
2017 615
2018 631




The following is the chart for the number of cities in ACS1 and ACS1/Subject, which are same for both API.


Year | Number of Cities
-- | --
2010 | 556
2011 | 563
2012 | 569
2013 | 583
2014 | 592
2015 | 597
2016 | 606
2017 | 615
2018 | 631

When I checked each year's cities that are added, most of the cities' populations are around 65,000. Therefore, it is added when the population estimates as 65,000. <bR>

I will check with other variables (SEX, RACE, Ethnicity) to find out how many cities that we want to use. Yet, my minimum will 556 because it is the number of cities from 2010.  <br>

I found out that one city with -999999, which is The Villages CDP, Florida	-999999999. I look for meaning. 

# Sex

For Sex, I want to find out right variable to use constantly throughout the year because in some year, it may give us proportion.<br>

For Sex, ACS has two main variables.

B01001_002E --> Estimate!!Total!!Male <Br>
B01001_026E --> Estimate!!Total!!Female
    
<br>
    These two variables that are constant throughout 2010-2018, which means that these two variables are same variables with the same label and concepts from the Census API and its format are the same. 


In [19]:

dic = {}
for year in range(2010,2019):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,B01001_001E,B01001_002E,B01001_026E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic[year] = data


2010 556
2011 563
2012 569
2013 583
2014 592
2015 597
2016 606
2017 615
2018 631


In [20]:
cols_sex= ['NAME', 'Pop_Total','Pop_Male', 'Pop_Female','Fips_State', 'Fips_Place']

# Set up each year's dataset

cities_2010 = pd.DataFrame(dic[2010][1:], columns=cols_sex)
cities_2010["Year"]=2010


cities_2011 = pd.DataFrame(dic[2011][1:], columns=cols_sex)
cities_2011["Year"]=2011


cities_2012 = pd.DataFrame(dic[2012][1:], columns=cols_sex)
cities_2012["Year"]=2012

cities_2013 = pd.DataFrame(dic[2013][1:], columns=cols_sex)
cities_2013["Year"]=2013


cities_2014 = pd.DataFrame(dic[2014][1:], columns=cols_sex)
cities_2014["Year"]=2014


cities_2015 = pd.DataFrame(dic[2015][1:], columns=cols_sex)
cities_2015["Year"]=2015

cities_2016 = pd.DataFrame(dic[2016][1:], columns=cols_sex)
cities_2016["Year"]=2016

cities_2017 = pd.DataFrame(dic[2017][1:], columns=cols_sex)
cities_2017["Year"]=2017

cities_2018 = pd.DataFrame(dic[2018][1:], columns=cols_sex)
cities_2018["Year"]=2018

In [21]:
cities_2010.head()

NAME Pop_Total Pop_Male Pop_Female Fips_State  \
0  Birmingham city, Alabama    211670    98760     112910         01   
1      Dothan city, Alabama     66121    31087      35034         01   
2      Hoover city, Alabama     80376    38694      41682         01   
3  Huntsville city, Alabama    181126    88132      92994         01   
4      Mobile city, Alabama    195249    91746     103503         01   

  Fips_Place  Year  
0      07000  2010  
1      21184  2010  
2      35896  2010  
3      37000  2010  
4      50000  2010

## Check whether any dataset from 2010 has no-value or none on sex population.

Explanantion, as each year's database has been setup, I want to check whether any cities has no-value or none.

In [22]:

print(cities_2010.isnull().sum().sum())
print(cities_2011.isnull().sum().sum())
print(cities_2012.isnull().sum().sum())
print(cities_2013.isnull().sum().sum())
print(cities_2014.isnull().sum().sum())
print(cities_2015.isnull().sum().sum())
print(cities_2016.isnull().sum().sum())
print(cities_2017.isnull().sum().sum())
print(cities_2018.isnull().sum().sum())

0
0
0
0
3
3
3
3
3


In [23]:

def findnanrows(df):
    
    is_NaN = df.isnull()
    row_has_NaN = is_NaN.any(axis=1)
    rows_with_NaN = df[row_has_NaN]
    return rows_with_NaN

In [24]:
findnanrows(cities_2015)

NAME Pop_Total Pop_Male Pop_Female Fips_State  \
570  The Villages CDP, Florida      None     None       None         12   

    Fips_Place  Year  
570      71625  2015

In [25]:
findnanrows(cities_2016)

NAME Pop_Total Pop_Male Pop_Female Fips_State  \
252  The Villages CDP, Florida      None     None       None         12   

    Fips_Place  Year  
252      71625  2016

In [26]:
findnanrows(cities_2017)

NAME Pop_Total Pop_Male Pop_Female Fips_State  \
596  The Villages CDP, Florida      None     None       None         12   

    Fips_Place  Year  
596      71625  2017

In [27]:
findnanrows(cities_2018)

NAME Pop_Total Pop_Male Pop_Female Fips_State  \
404  The Villages CDP, Florida      None     None       None         12   

    Fips_Place  Year  
404      71625  2018

The Villages CDP, Florida is the only city with no value in the Male and Female population. Also, it is none the population as well. 
Therefore, I will check with other variables, then if this city does not have numbers from all variables, I will exclude it. 

In [28]:

# Combine all SEX group
frames = [cities_2010, cities_2011, cities_2012, cities_2013,cities_2014,\
          cities_2015,cities_2016, cities_2017, cities_2018]

sex_result = pd.concat(frames)

In [29]:
sex_result.head()

NAME Pop_Total Pop_Male Pop_Female Fips_State  \
0  Birmingham city, Alabama    211670    98760     112910         01   
1      Dothan city, Alabama     66121    31087      35034         01   
2      Hoover city, Alabama     80376    38694      41682         01   
3  Huntsville city, Alabama    181126    88132      92994         01   
4      Mobile city, Alabama    195249    91746     103503         01   

  Fips_Place  Year  
0      07000  2010  
1      21184  2010  
2      35896  2010  
3      37000  2010  
4      50000  2010

In [30]:
sex_result['Fips_State_Place']=sex_result['Fips_State']+sex_result['Fips_Place']

In [31]:
sex_result.tail()

NAME Pop_Total Pop_Male Pop_Female Fips_State  \
625         Menifee city, California     92602    46509      46093         06   
626       Riverside city, California    330080   160110     169970         06   
627  Springfield city, Massachusetts    155029    75821      79208         25   
628          Dale City CDP, Virginia     68805    35840      32965         51   
629      South Gate city, California     94439    47917      46522         06   

    Fips_Place  Year Fips_State_Place  
625      46842  2018          0646842  
626      62000  2018          0662000  
627      67000  2018          2567000  
628      21088  2018          5121088  
629      73080  2018          0673080

In [32]:
# Creating NYU_500_Largest to find out whether NYU dataset has this city or not.

# Pull out NYU FIPS 
# Preselect column type as object
coltype = {'fips_state':object,
          'fips_place':object,
           'fips_state_place':object}
nyu = pd.read_csv(r"/Users/jasonlim/Desktop/EFGS/Census-master/CitiesDataset/City_Health_data/nyu_fips_code.csv",\
                  dtype= coltype)


In [33]:
nyu.head()

index state_abb fips_state fips_place fips_state_place   city_name
0      0        HI         15      00003          0015003    Honolulu
1      1        AL         01      07000          0107000  Birmingham
2      2        AL         01      35896          0135896      Hoover
3      3        AL         01      37000          0137000  Huntsville
4      4        AL         01      50000          0150000      Mobile

In [34]:
nyu_cities = list(nyu['fips_state_place'])

In [35]:
sex_result['NYU_500_Largest'] = sex_result['Fips_State_Place'].apply(lambda x:1 if x in nyu_cities else 0)

In [36]:
sex_result.head()

NAME Pop_Total Pop_Male Pop_Female Fips_State  \
0  Birmingham city, Alabama    211670    98760     112910         01   
1      Dothan city, Alabama     66121    31087      35034         01   
2      Hoover city, Alabama     80376    38694      41682         01   
3  Huntsville city, Alabama    181126    88132      92994         01   
4      Mobile city, Alabama    195249    91746     103503         01   

  Fips_Place  Year Fips_State_Place  NYU_500_Largest  
0      07000  2010          0107000                1  
1      21184  2010          0121184                0  
2      35896  2010          0135896                1  
3      37000  2010          0137000                1  
4      50000  2010          0150000                1

In [37]:
#sex_result.to_csv("wave2_first.csv", index=False)

In [38]:
len(nyu_cities)

510

In [39]:
495/len(nyu_cities)

0.9705882352941176

## Checking How many NYU cities were covered in each year

From NYu cities 510, ACS1 can cover 495-496 cities, which is around 97%

In [40]:
sex_result.groupby('Year').sum()

NYU_500_Largest
Year                 
2010              496
2011              496
2012              496
2013              496
2014              495
2015              495
2016              495
2017              495
2018              495

As shown above, from 509 cities of NYU dataset, 495/ 496 cities are covered by ACS1. Most of cities are covered by ACS1.

# Race

For Race, I want to find out right variable to use constantly throughout the year because in some year, it may give us proportion.<br>

For Race, ACS B02001 Group has five main variables for race.<br>

B02001_002E	-->Estimate!!Total!!White alone<br>
B02001_003E	-->Estimate!!Total!!Black or African American alone<br>
B02001_005E	-->Estimate!!Total!!Asian alone<br>
B02001_004E	-->Estimate!!Total!!American Indian and Alaska Native alone<br>
B02001_006E -->Estimate!!Total!!Native Hawaiian and Other Pacific Islander alone <Br>

These five variables have constant methods, which is the whole number, throughout 2010-2018

In [41]:

dic = {}
for year in range(2010,2019):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,B02001_002E,B02001_003E,B02001_005E,B02001_004E,B02001_006E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic[year] = data


2010 556
2011 563
2012 569
2013 583
2014 592
2015 597
2016 606
2017 615
2018 631


In [42]:
cols_race= ['NAME', 'Pop_White','Pop_Black','Pop_Asian','Pop_AIAN','Pop_NHOPI','Fips_State', 'Fips_Place']

# Set up each year's dataset

cities_2010_r = pd.DataFrame(dic[2010][1:], columns=cols_race)
cities_2010_r["Year"]=2010


cities_2011_r = pd.DataFrame(dic[2011][1:], columns=cols_race)
cities_2011_r["Year"]=2011


cities_2012_r = pd.DataFrame(dic[2012][1:], columns=cols_race)
cities_2012_r["Year"]=2012

cities_2013_r = pd.DataFrame(dic[2013][1:], columns=cols_race)
cities_2013_r["Year"]=2013


cities_2014_r = pd.DataFrame(dic[2014][1:], columns=cols_race)
cities_2014_r["Year"]=2014


cities_2015_r = pd.DataFrame(dic[2015][1:], columns=cols_race)
cities_2015_r["Year"]=2015

cities_2016_r = pd.DataFrame(dic[2016][1:], columns=cols_race)
cities_2016_r["Year"]=2016

cities_2017_r = pd.DataFrame(dic[2017][1:], columns=cols_race)
cities_2017_r["Year"]=2017

cities_2018_r = pd.DataFrame(dic[2018][1:], columns=cols_race)
cities_2018_r["Year"]=2018

In [43]:
cities_2010_r.head()

NAME Pop_White Pop_Black Pop_Asian Pop_AIAN Pop_NHOPI  \
0  Birmingham city, Alabama     47657    158193      1528      593         0   
1      Dothan city, Alabama     41867     21123       916      186         0   
2      Hoover city, Alabama     57507     11555      5345      235         0   
3  Huntsville city, Alabama    114796     53460      5734      434       161   
4      Mobile city, Alabama     89418     98746      2621      474        53   

  Fips_State Fips_Place  Year  
0         01      07000  2010  
1         01      21184  2010  
2         01      35896  2010  
3         01      37000  2010  
4         01      50000  2010

## Check whether any dataset from 2010 has no-value or none on Race population.

Explanantion, as each year's database has been setup, I want to check whether any cities has no-value or none.

In [44]:

print(cities_2010_r.isnull().sum().sum())
print(cities_2011_r.isnull().sum().sum())
print(cities_2012_r.isnull().sum().sum())
print(cities_2013_r.isnull().sum().sum())
print(cities_2014_r.isnull().sum().sum())
print(cities_2015_r.isnull().sum().sum())
print(cities_2016_r.isnull().sum().sum())
print(cities_2017_r.isnull().sum().sum())
print(cities_2018_r.isnull().sum().sum())

95
125
45
60
55
75
70
60
90


In [45]:
findnanrows(cities_2010_r)

NAME Pop_White Pop_Black Pop_Asian  \
536         East Orange city, New Jersey      None      None      None   
537                  Mission city, Texas      None      None      None   
538                  Troy city, Michigan      None      None      None   
539          Ellicott City CDP, Maryland      None      None      None   
540                 Meridian city, Idaho      None      None      None   
541              O'Fallon city, Missouri      None      None      None   
542       Rock Hill city, South Carolina      None      None      None   
543                     Sandy city, Utah      None      None      None   
544  Mount Pleasant town, South Carolina      None      None      None   
545            Jackson city, Mississippi      None      None      None   
546             Jonesboro city, Arkansas      None      None      None   
547                    Pharr city, Texas      None      None      None   
548             Lynwood city, California      None      None      None   
549               Suffolk city, Virginia      None      None      None   
550          Boynton Beach city, Florida      None      None      None   
551           Eau Claire city, Wisconsin      None      None      None   
552          Miami Gardens city, Florida      None      None      None   
553             Flower Mound town, Texas      None      None      None   
554                Fishers town, Indiana      None      None      None   

    Pop_AIAN Pop_NHOPI Fips_State Fips_Place  Year  
536     None      None         34      19390  2010  
537     None      None         48      48768  2010  
538     None      None         26      80700  2010  
539     None      None         24      26000  2010  
540     None      None         16      52120  2010  
541     None      None         29      54074  2010  
542     None      None         45      61405  2010  
543     None      None         49      67440  2010  
544     None      None         45      48535  2010  
545     None      None         28      36000  2010  
546     None      None         05      35710  2010  
547     None      None         48      57200  2010  
548     None      None         06      44574  2010  
549     None      None         51      76432  2010  
550     None      None         12      07875  2010  
551     None      None         55      22300  2010  
552     None      None         12      45060  2010  
553     None      None         48      26232  2010  
554     None      None         18      23278  2010

In [46]:
findnanrows(cities_2011_r)

NAME Pop_White Pop_Black Pop_Asian  \
537                 Albany city, Georgia      None      None      None   
538                  Mission city, Texas      None      None      None   
539          Ellicott City CDP, Maryland      None      None      None   
540                 Meridian city, Idaho      None      None      None   
541                 Portland city, Maine      None      None      None   
542             Lauderhill city, Florida      None      None      None   
543           Gulfport city, Mississippi      None      None      None   
544            Johns Creek city, Georgia      None      None      None   
545              O'Fallon city, Missouri      None      None      None   
546                Cicero town, Illinois      None      None      None   
547  Mount Pleasant town, South Carolina      None      None      None   
548             Jonesboro city, Arkansas      None      None      None   
549               Avondale city, Arizona      None      None      None   
550                    Canton city, Ohio      None      None      None   
551               Surprise city, Arizona      None      None      None   
552                 Alafaya CDP, Florida      None      None      None   
553                    Pharr city, Texas      None      None      None   
554        Deerfield Beach city, Florida      None      None      None   
555             Tuscaloosa city, Alabama      None      None      None   
556         Lake Charles city, Louisiana      None      None      None   
557          Miami Gardens city, Florida      None      None      None   
558             Fort Myers city, Florida      None      None      None   
559             Flower Mound town, Texas      None      None      None   
560                  Macon city, Georgia      None      None      None   
561                 Kendall CDP, Florida      None      None      None   

    Pop_AIAN Pop_NHOPI Fips_State Fips_Place  Year  
537     None      None         13      01052  2011  
538     None      None         48      48768  2011  
539     None      None         24      26000  2011  
540     None      None         16      52120  2011  
541     None      None         23      60545  2011  
542     None      None         12      39550  2011  
543     None      None         28      29700  2011  
544     None      None         13      42425  2011  
545     None      None         29      54074  2011  
546     None      None         17      14351  2011  
547     None      None         45      48535  2011  
548     None      None         05      35710  2011  
549     None      None         04      04720  2011  
550     None      None         39      12000  2011  
551     None      None         04      71510  2011  
552     None      None         12      00410  2011  
553     None      None         48      57200  2011  
554     None      None         12      16725  2011  
555     None      None         01      77256  2011  
556     None      None         22      41155  2011  
557     None      None         12      45060  2011  
558     None      None         12      24125  2011  
559     None      None         48      26232  2011  
560     None      None         13      49000  2011  
561     None      None         12      36100  2011

## Different Census API Groups for Race
Try to look for different variables since Census API have around 50-100 cities missing for Race.<br>
B02003 Group is also race categories. I want to check whether it has more information than B02001 Group.<Br>
    
    
B02003_003E	-->Estimate!!Total!!White alone<br>
B02003_004E	-->Estimate!!Total!!Black or African American alone<br>
B02003_006E	-->Estimate!!Total!!Asian alone<br>
B02003_005E	-->Estimate!!Total!!American Indian and Alaska Native alone<br>
B02003_007E -->Estimate!!Total!!Native Hawaiian and Other Pacific Islander alone <Br>

In [47]:

dic_1 = {}
for year in range(2010,2019):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,B02003_003E,B02003_004E,B02003_006E,B02003_005E,B02003_007E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic_1[year] = data


2010 556
2011 563
2012 569
2013 583
2014 592
2015 597
2016 606
2017 615
2018 631


In [48]:


# Set up each year's dataset

cities_2010_r1 = pd.DataFrame(dic_1[2010][1:], columns=cols_race)
cities_2010_r1["Year"]=2010


cities_2011_r1 = pd.DataFrame(dic_1[2011][1:], columns=cols_race)
cities_2011_r1["Year"]=2011


cities_2012_r1 = pd.DataFrame(dic_1[2012][1:], columns=cols_race)
cities_2012_r1["Year"]=2012

cities_2013_r1 = pd.DataFrame(dic_1[2013][1:], columns=cols_race)
cities_2013_r1["Year"]=2013


cities_2014_r1 = pd.DataFrame(dic_1[2014][1:], columns=cols_race)
cities_2014_r1["Year"]=2014


cities_2015_r1 = pd.DataFrame(dic_1[2015][1:], columns=cols_race)
cities_2015_r1["Year"]=2015

cities_2016_r1 = pd.DataFrame(dic_1[2016][1:], columns=cols_race)
cities_2016_r1["Year"]=2016

cities_2017_r1 = pd.DataFrame(dic_1[2017][1:], columns=cols_race)
cities_2017_r1["Year"]=2017

cities_2018_r1 = pd.DataFrame(dic_1[2018][1:], columns=cols_race)
cities_2018_r1["Year"]=2018



print(cities_2010_r1.isnull().sum().sum())
print(cities_2011_r1.isnull().sum().sum())
print(cities_2012_r1.isnull().sum().sum())
print(cities_2013_r1.isnull().sum().sum())
print(cities_2014_r1.isnull().sum().sum())
print(cities_2015_r1.isnull().sum().sum())
print(cities_2016_r1.isnull().sum().sum())
print(cities_2017_r1.isnull().sum().sum())
print(cities_2018_r1.isnull().sum().sum())

2770
2810
2840
2910
2955
2980
3025
3070
3150


In [49]:
cities_2010_r1.head()

NAME Pop_White Pop_Black Pop_Asian Pop_AIAN Pop_NHOPI  \
0  Birmingham city, Alabama      None      None      None     None      None   
1      Dothan city, Alabama      None      None      None     None      None   
2      Hoover city, Alabama      None      None      None     None      None   
3  Huntsville city, Alabama      None      None      None     None      None   
4      Mobile city, Alabama      None      None      None     None      None   

  Fips_State Fips_Place  Year  
0         01      07000  2010  
1         01      21184  2010  
2         01      35896  2010  
3         01      37000  2010  
4         01      50000  2010

**B02003 group is uselss in here because the group is mostly with empty variables.** <Br>
So, I decide not to use this group.


There is one other group of race which are the following:<br>

B02008_001E --> Estimate!!Total!WHITE ALONE OR IN COMBINATION WITH ONE OR MORE OTHER RACES<br>
B02009_001E -->BLACK OR AFRICAN AMERICAN ALONE OR IN COMBINATION WITH ONE OR MORE OTHER RACES<br>
B02010_001E -->AMERICAN INDIAN AND ALASKA NATIVE ALONE OR IN COMBINATION WITH ONE OR MORE OTHER RACES<br>
B02011_001E --> ASIAN ALONE OR IN COMBINATION WITH ONE OR MORE OTHER RACES<br>
B02012_001E -->NATIVE HAWAIIAN AND OTHER PACIFIC ISLANDER ALONE OR IN COMBINATION WITH ONE OR MORE OTHER RACES<br>

In [50]:

dic_2 = {}
for year in range(2010,2019):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,B02008_001E,B02009_001E,B02011_001E,B02010_001E,B02012_001E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic_2[year] = data


2010 556
2011 563
2012 569
2013 583
2014 592
2015 597
2016 606
2017 615
2018 631


In [51]:


# Set up each year's dataset

cities_2010_r2 = pd.DataFrame(dic_2[2010][1:], columns=cols_race)
cities_2010_r2["Year"]=2010


cities_2011_r2 = pd.DataFrame(dic_2[2011][1:], columns=cols_race)
cities_2011_r2["Year"]=2011


cities_2012_r2 = pd.DataFrame(dic_2[2012][1:], columns=cols_race)
cities_2012_r2["Year"]=2012

cities_2013_r2 = pd.DataFrame(dic_2[2013][1:], columns=cols_race)
cities_2013_r2["Year"]=2013


cities_2014_r2 = pd.DataFrame(dic_2[2014][1:], columns=cols_race)
cities_2014_r2["Year"]=2014


cities_2015_r2 = pd.DataFrame(dic_2[2015][1:], columns=cols_race)
cities_2015_r2["Year"]=2015

cities_2016_r2 = pd.DataFrame(dic_2[2016][1:], columns=cols_race)
cities_2016_r2["Year"]=2016

cities_2017_r2 = pd.DataFrame(dic_2[2017][1:], columns=cols_race)
cities_2017_r2["Year"]=2017

cities_2018_r2 = pd.DataFrame(dic_2[2018][1:], columns=cols_race)
cities_2018_r2["Year"]=2018



print(cities_2010_r2.isnull().sum().sum())
print(cities_2011_r2.isnull().sum().sum())
print(cities_2012_r2.isnull().sum().sum())
print(cities_2013_r2.isnull().sum().sum())
print(cities_2014_r2.isnull().sum().sum())
print(cities_2015_r2.isnull().sum().sum())
print(cities_2016_r2.isnull().sum().sum())
print(cities_2017_r2.isnull().sum().sum())
print(cities_2018_r2.isnull().sum().sum())

479
464
415
438
411
440
450
478
499


**No value rows are less than B02003 Group, but still more than B02001 Group.**

### For Race, I decide to use B02001 group, which I picked at the first.

In [52]:

# Combine all race group
frames_r = [cities_2010_r, cities_2011_r, cities_2012_r, cities_2013_r,\
            cities_2014_r,cities_2015_r,cities_2016_r, cities_2017_r, cities_2018_r]
# Concat all years from 2010-2018
race_result = pd.concat(frames_r)
# Creating columns from fips_state_place for joining the with sex
race_result['Fips_State_Place']=race_result['Fips_State']+race_result['Fips_Place']

In [53]:
race_result.tail()

NAME Pop_White Pop_Black Pop_Asian Pop_AIAN  \
625         Alpharetta city, Georgia      None      None      None     None   
626  Caguas zona urbana, Puerto Rico      None      None      None     None   
627     Lake Charles city, Louisiana      None      None      None     None   
628            Harlingen city, Texas      None      None      None     None   
629                Ankeny city, Iowa      None      None      None     None   

    Pop_NHOPI Fips_State Fips_Place  Year Fips_State_Place  
625      None         13      01696  2018          1301696  
626      None         72      10334  2018          7210334  
627      None         22      41155  2018          2241155  
628      None         48      32372  2018          4832372  
629      None         19      02305  2018          1902305

In [54]:
wave_2_sec = pd.merge(sex_result , race_result, how='left',on=['Fips_State_Place','Year','NAME','Fips_State', 'Fips_Place'])

In [55]:
wave_2_sec.head(10)

NAME Pop_Total Pop_Male Pop_Female Fips_State  \
0        Birmingham city, Alabama    211670    98760     112910         01   
1            Dothan city, Alabama     66121    31087      35034         01   
2            Hoover city, Alabama     80376    38694      41682         01   
3        Huntsville city, Alabama    181126    88132      92994         01   
4            Mobile city, Alabama    195249    91746     103503         01   
5        Montgomery city, Alabama    206655    97605     109050         01   
6        Tuscaloosa city, Alabama     90637    43997      46640         01   
7  Anchorage municipality, Alaska    293227   148566     144661         02   
8          Avondale city, Arizona     76446    39206      37240         04   
9          Chandler city, Arizona    236775   116459     120316         04   

  Fips_Place  Year Fips_State_Place  NYU_500_Largest Pop_White Pop_Black  \
0      07000  2010          0107000                1     47657    158193   
1      21184  2010          0121184                0     41867     21123   
2      35896  2010          0135896                1     57507     11555   
3      37000  2010          0137000                1    114796     53460   
4      50000  2010          0150000                1     89418     98746   
5      51000  2010          0151000                1     78817    115853   
6      77256  2010          0177256                1     48895     38870   
7      03000  2010          0203000                1    195553     17874   
8      04720  2010          0404720                1     59236      6888   
9      12000  2010          0412000                1    181872     12980   

  Pop_Asian Pop_AIAN Pop_NHOPI  
0      1528      593         0  
1       916      186         0  
2      5345      235         0  
3      5734      434       161  
4      2621      474        53  
5      4368      571        90  
6       861        0         0  
7     23986    21787      6388  
8      1557     1039       189  
9     24702     1834       384

In [56]:
wave_2_sec.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5303 entries, 0 to 5302
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   NAME              5303 non-null   object
 1   Pop_Total         5298 non-null   object
 2   Pop_Male          5298 non-null   object
 3   Pop_Female        5298 non-null   object
 4   Fips_State        5303 non-null   object
 5   Fips_Place        5303 non-null   object
 6   Year              5303 non-null   int64 
 7   Fips_State_Place  5303 non-null   object
 8   NYU_500_Largest   5303 non-null   int64 
 9   Pop_White         5168 non-null   object
 10  Pop_Black         5168 non-null   object
 11  Pop_Asian         5168 non-null   object
 12  Pop_AIAN          5168 non-null   object
 13  Pop_NHOPI         5168 non-null   object
dtypes: int64(2), object(12)
memory usage: 621.4+ KB


## Ethnicity

For Ethnicity, ACS B02001 Group has two main variables for ethnicity.<br>

B03001_002E	-->Estimate!!Total!!Not Hispanic or Latino<br>
B03001_003E	-->Estimate!!Total!!Hispanic or Latino<br>


These two variables have constant methods, which is the whole number, throughout 2010-2018


In [57]:

dic_e = {}
for year in range(2010,2019):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,B03001_002E,B03001_003E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic_e[year] = data


2010 556
2011 563
2012 569
2013 583
2014 592
2015 597
2016 606
2017 615
2018 631


In [58]:
cols_eth= ['NAME', 'Pop_Nonhispanic','Pop_Hispanic','Fips_State', 'Fips_Place']

# Set up each year's dataset

cities_2010_e = pd.DataFrame(dic_e[2010][1:], columns=cols_eth)
cities_2010_e["Year"]=2010


cities_2011_e = pd.DataFrame(dic_e[2011][1:], columns=cols_eth)
cities_2011_e["Year"]=2011


cities_2012_e = pd.DataFrame(dic_e[2012][1:], columns=cols_eth)
cities_2012_e["Year"]=2012

cities_2013_e = pd.DataFrame(dic_e[2013][1:], columns=cols_eth)
cities_2013_e["Year"]=2013


cities_2014_e = pd.DataFrame(dic_e[2014][1:], columns=cols_eth)
cities_2014_e["Year"]=2014


cities_2015_e = pd.DataFrame(dic_e[2015][1:], columns=cols_eth)
cities_2015_e["Year"]=2015

cities_2016_e = pd.DataFrame(dic_e[2016][1:], columns=cols_eth)
cities_2016_e["Year"]=2016

cities_2017_e = pd.DataFrame(dic_e[2017][1:], columns=cols_eth)
cities_2017_e["Year"]=2017

cities_2018_e = pd.DataFrame(dic_e[2018][1:], columns=cols_eth)
cities_2018_e["Year"]=2018



print(cities_2010_e.isnull().sum().sum())
print(cities_2011_e.isnull().sum().sum())
print(cities_2012_e.isnull().sum().sum())
print(cities_2013_e.isnull().sum().sum())
print(cities_2014_e.isnull().sum().sum())
print(cities_2015_e.isnull().sum().sum())
print(cities_2016_e.isnull().sum().sum())
print(cities_2017_e.isnull().sum().sum())
print(cities_2018_e.isnull().sum().sum())

1044
1054
1044
1088
1094
1090
1110
1128
1164


In [59]:
# Check data without no-value
cities_2010_e.dropna()

NAME Pop_Nonhispanic Pop_Hispanic  \
0                   Phoenix city, Arizona          877736       571745   
1                Anaheim city, California          155244       182015   
2             Long Beach city, California          266596       196197   
3            Los Angeles city, California         1943870      1853274   
4                Oakland city, California          294157        97515   
5              San Diego city, California          929831       382055   
6          San Francisco city, California          683273       122190   
7               San Jose city, California          630808       318389   
8                   Aurora city, Colorado          227038        99681   
9   Washington city, District of Columbia          549197        55256   
10                  Hialeah city, Florida            7216       218245   
11                Hollywood city, Florida           99811        41391   
12             Jacksonville city, Florida          759235        64081   
13                   Kendall CDP, Florida           31441        51120   
14                    Miami city, Florida          116799       284093   
15              Miami Beach city, Florida           41262        46848   
16           Pembroke Pines city, Florida           90140        65112   
17                    Tampa city, Florida          262395        74550   
18                 Chicago city, Illinois         1934863       763968   
19             Boston city, Massachusetts          516516       104867   
20                 Las Vegas city, Nevada          402718       181923   
21             Elizabeth city, New Jersey           49877        75345   
22                Newark city, New Jersey          184703        92529   
23                New York city, New York         5838073      2346826   
24         Charlotte city, North Carolina          638172        96246   
25        Philadelphia city, Pennsylvania         1339803       188503   
26                     Austin city, Texas          507388       288130   
27                     Dallas city, Texas          690820       511977   
28                 Fort Worth city, Texas          494042       250072   
29                    Houston city, Texas         1189215       917993   
30                San Antonio city, Texas          480705       853654   
31                Arlington CDP, Virginia          177720        31737   
32               Seattle city, Washington          573849        36861   

   Fips_State Fips_Place  Year  
0          04      55000  2010  
1          06      02000  2010  
2          06      43000  2010  
3          06      44000  2010  
4          06      53000  2010  
5          06      66000  2010  
6          06      67000  2010  
7          06      68000  2010  
8          08      04000  2010  
9          11      50000  2010  
10         12      30000  2010  
11         12      32000  2010  
12         12      35000  2010  
13         12      36100  2010  
14         12      45000  2010  
15         12      45025  2010  
16         12      55775  2010  
17         12      71000  2010  
18         17      14000  2010  
19         25      07000  2010  
20         32      40000  2010  
21         34      21000  2010  
22         34      51000  2010  
23         36      51000  2010  
24         37      12000  2010  
25         42      60000  2010  
26         48      05000  2010  
27         48      19000  2010  
28         48      27000  2010  
29         48      35000  2010  
30         48      65000  2010  
31         51      03000  2010  
32         53      63000  2010

In 2010, there are only 33 cities with Ethnicity. So, 470 cities are without Ethnicity variables.<Br>
Need to look different variables. <br>
    
    B03002 group is also Ethnicity group
    
    B03002_002E --> Estimate!!Total!!Not Hispanic or Latino
    B03002_012E --> Estimate!!Total!!Hispanic or Latino

In [60]:

dic_e1 = {}
for year in range(2010,2019):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,B03002_002E,B03002_012E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic_e1[year] = data


2010 556
2011 563
2012 569
2013 583
2014 592
2015 597
2016 606
2017 615
2018 631


In [61]:


# Set up each year's dataset

cities_2010_e1 = pd.DataFrame(dic_e1[2010][1:], columns=cols_eth)
cities_2010_e1["Year"]=2010


cities_2011_e1 = pd.DataFrame(dic_e1[2011][1:], columns=cols_eth)
cities_2011_e1["Year"]=2011


cities_2012_e1 = pd.DataFrame(dic_e1[2012][1:], columns=cols_eth)
cities_2012_e1["Year"]=2012

cities_2013_e1 = pd.DataFrame(dic_e1[2013][1:], columns=cols_eth)
cities_2013_e1["Year"]=2013


cities_2014_e1 = pd.DataFrame(dic_e1[2014][1:], columns=cols_eth)
cities_2014_e1["Year"]=2014


cities_2015_e1 = pd.DataFrame(dic_e1[2015][1:], columns=cols_eth)
cities_2015_e1["Year"]=2015

cities_2016_e1 = pd.DataFrame(dic_e1[2016][1:], columns=cols_eth)
cities_2016_e1["Year"]=2016

cities_2017_e1 = pd.DataFrame(dic_e1[2017][1:], columns=cols_eth)
cities_2017_e1["Year"]=2017

cities_2018_e1 = pd.DataFrame(dic_e1[2018][1:], columns=cols_eth)
cities_2018_e1["Year"]=2018



print(cities_2010_e1.isnull().sum().sum())
print(cities_2011_e1.isnull().sum().sum())
print(cities_2012_e1.isnull().sum().sum())
print(cities_2013_e1.isnull().sum().sum())
print(cities_2014_e1.isnull().sum().sum())
print(cities_2015_e1.isnull().sum().sum())
print(cities_2016_e1.isnull().sum().sum())
print(cities_2017_e1.isnull().sum().sum())
print(cities_2018_e1.isnull().sum().sum())

560
582
500
528
516
552
530
580
584


In [62]:
cities_2010_e1

NAME Pop_Nonhispanic  \
0                             Huntsville city, Alabama          170562   
1                       Anchorage municipality, Alaska          270925   
2                               Chandler city, Arizona          180028   
3                              Flagstaff city, Arizona           54703   
4                                Gilbert town, Arizona          180642   
5                               Glendale city, Arizona          141901   
6                                   Mesa city, Arizona          324773   
7                                 Peoria city, Arizona          122187   
8                                Phoenix city, Arizona          877736   
9                                  Tempe city, Arizona          127900   
10                                Tucson city, Arizona          309756   
11                                  Yuma city, Arizona           40308   
12                            Alameda city, California           64946   
13                            Anaheim city, California          155244   
14                            Antioch city, California           61143   
15                        Arden-Arcade CDP, California           67522   
16                        Bakersfield city, California          186631   
17                           Berkeley city, California          100839   
18                         Buena Park city, California           50095   
19                             Carson city, California           58656   
20                              Chico city, California           72373   
21                              Chino city, California           33284   
22                        Chino Hills city, California           47363   
23                        Chula Vista city, California          109018   
24                     Citrus Heights city, California           68089   
25                             Clovis city, California           70572   
26                            Concord city, California           90511   
27                             Corona city, California           89151   
28                         Costa Mesa city, California           66662   
29                          Daly City city, California           76768   
30                    East Los Angeles CDP, California            3190   
31                           El Cajon city, California           70350   
32                          Elk Grove city, California          124091   
33                          Escondido city, California           78060   
34                          Fairfield city, California           77836   
35                            Fontana city, California           74594   
36                            Fremont city, California          181072   
37                             Fresno city, California          264057   
38                          Fullerton city, California           85487   
39                       Garden Grove city, California          113134   
40                           Glendale city, California          159506   
41                          Hawthorne city, California           39370   
42                            Hayward city, California           84898   
43                           Hesperia city, California           51745   
44                   Huntington Beach city, California          156045   
45                          Inglewood city, California           52398   
46                             Irvine city, California          192011   
47                           Lakewood city, California           50546   
48                          Lancaster city, California          101194   
49                         Long Beach city, California          266596   
50                        Los Angeles city, California         1943870   
51                            Manteca city, California           43396   
52                             Merced city, California           43118   
53                            Modesto city, California

Final group for Ethnicity is B03003 for HISPANIC OR LATINO ORIGIN <br>
B03003_001E	Estimate!!Total <br>
B03003_002E	Estimate!!Total!!Not Hispanic or Latino  <br>
B03003_003E	Estimate!!Total!!Hispanic or Latino <Br>

In [63]:

dic_e2 = {}
for year in range(2010,2019):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,B03003_001E,B03003_002E,B03003_003E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic_e2[year] = data


2010 556
2011 563
2012 569
2013 583
2014 592
2015 597
2016 606
2017 615
2018 631


In [64]:
cols_e2th= ['NAME', 'total_pop','Pop_Nonhispanic','Pop_Hispanic','Fips_State', 'Fips_Place']

# Set up each year's dataset

cities_2010_e2 = pd.DataFrame(dic_e2[2010][1:], columns=cols_e2th)
cities_2010_e2["Year"]=2010


cities_2011_e2 = pd.DataFrame(dic_e2[2011][1:], columns=cols_e2th)
cities_2011_e2["Year"]=2011


cities_2012_e2 = pd.DataFrame(dic_e2[2012][1:], columns=cols_e2th)
cities_2012_e2["Year"]=2012

cities_2013_e2 = pd.DataFrame(dic_e2[2013][1:], columns=cols_e2th)
cities_2013_e2["Year"]=2013


cities_2014_e2 = pd.DataFrame(dic_e2[2014][1:], columns=cols_e2th)
cities_2014_e2["Year"]=2014


cities_2015_e2 = pd.DataFrame(dic_e2[2015][1:], columns=cols_e2th)
cities_2015_e2["Year"]=2015

cities_2016_e2 = pd.DataFrame(dic_e2[2016][1:], columns=cols_e2th)
cities_2016_e2["Year"]=2016

cities_2017_e2 = pd.DataFrame(dic_e2[2017][1:], columns=cols_e2th)
cities_2017_e2["Year"]=2017

cities_2018_e2 = pd.DataFrame(dic_e2[2018][1:], columns=cols_e2th)
cities_2018_e2["Year"]=2018



print(cities_2010_e2.isnull().sum().sum())
print(cities_2011_e2.isnull().sum().sum())
print(cities_2012_e2.isnull().sum().sum())
print(cities_2013_e2.isnull().sum().sum())
print(cities_2014_e2.isnull().sum().sum())
print(cities_2015_e2.isnull().sum().sum())
print(cities_2016_e2.isnull().sum().sum())
print(cities_2017_e2.isnull().sum().sum())
print(cities_2018_e2.isnull().sum().sum())

0
0
0
0
0
0
0
0
0


In [65]:
cities_2010_e2.tail()

NAME total_pop Pop_Nonhispanic Pop_Hispanic  \
550  Carolina zona urbana, Puerto Rico    160324            2897       157427   
551  Guaynabo zona urbana, Puerto Rico     72315            1204        71111   
552  Mayagüez zona urbana, Puerto Rico     71129            1453        69676   
553     Ponce zona urbana, Puerto Rico    134788             861       133927   
554  San Juan zona urbana, Puerto Rico    382900            8856       374044   

    Fips_State Fips_Place  Year  
550         72      14290  2010  
551         72      32522  2010  
552         72      52431  2010  
553         72      63820  2010  
554         72      76770  2010

There is no none value, so I will use B03003 group. 

In [66]:

# Combine all race group
frames_e = [cities_2010_e2, cities_2011_e2, cities_2012_e2, cities_2013_e2,cities_2014_e2,cities_2015_e2,cities_2016_e2, cities_2017_e2, cities_2018_e2]
# Concat all years from 2010-2018
eth_result = pd.concat(frames_e)
# Creating columns from fips_state_place for joining the with sex
eth_result['Fips_State_Place']=eth_result['Fips_State']+eth_result['Fips_Place']

In [67]:
# filter out total_pop because we do not need it anymore.

eth_result.drop('total_pop', axis=1, inplace=True)

In [68]:
wave_2_third = pd.merge(wave_2_sec , eth_result, how='left',on=['Fips_State_Place','Year','NAME','Fips_State', 'Fips_Place'])

In [69]:
wave_2_third.head()

NAME Pop_Total Pop_Male Pop_Female Fips_State  \
0  Birmingham city, Alabama    211670    98760     112910         01   
1      Dothan city, Alabama     66121    31087      35034         01   
2      Hoover city, Alabama     80376    38694      41682         01   
3  Huntsville city, Alabama    181126    88132      92994         01   
4      Mobile city, Alabama    195249    91746     103503         01   

  Fips_Place  Year Fips_State_Place  NYU_500_Largest Pop_White Pop_Black  \
0      07000  2010          0107000                1     47657    158193   
1      21184  2010          0121184                0     41867     21123   
2      35896  2010          0135896                1     57507     11555   
3      37000  2010          0137000                1    114796     53460   
4      50000  2010          0150000                1     89418     98746   

  Pop_Asian Pop_AIAN Pop_NHOPI Pop_Nonhispanic Pop_Hispanic  
0      1528      593         0          204155         7515  
1       916      186         0           64104         2017  
2      5345      235         0           72254         8122  
3      5734      434       161          170562        10564  
4      2621      474        53          190257         4992

In [70]:
#wave_2_third.to_csv("wave2_third.csv", index=False)


# Age Group

ACS1 table has its own age and sex grouping. <br> 
For example, Estimate!!Total!!Male!!15 to 17 years,     Estimate!!Total!!Male!!10 to 14 years<br>
Yet, the ACS1 table divides into Sex and/or race and grouped with different lengths of the years. Therefore, I decided to use the ACS1/subject dataset because it is grouped well and shows relevant age groups. 

For Age Group, from 2017, Under 18 years is added. It is useful to us, but it does not present in ACS1/subject table before 2016. The following are the variables and its name. 


Year | Under 18 years | 15 to 44 years | 18 years and over | 65 years and over
-- | -- | -- | -- | --
2010 | None | S0101_C01_023E | S0101_C01_025E | S0101_C01_028E
2011 | None | S0101_C01_023E | S0101_C01_025E | S0101_C01_028E
2012 | None | S0101_C01_023E | S0101_C01_025E | S0101_C01_028E
2013 | None | S0101_C01_023E | S0101_C01_025E | S0101_C01_028E
2014 | None | S0101_C01_023E | S0101_C01_025E | S0101_C01_028E
2015 | None | S0101_C01_023E | S0101_C01_025E | S0101_C01_028E
2016 | None | S0101_C01_023E | S0101_C01_025E | S0101_C01_028E
2017 | S0101_C02_022E | S0101_C02_024E | S0101_C02_026E | S0101_C02_030E
2018 | S0101_C02_022E | S0101_C02_024E | S0101_C02_026E | S0101_C02_030E


I can calculate Under 18 using total population - population for 18years and over. Yet, I will try to gather pure dataset first, so I decide to eliminate Under 18 years from Age group. <br>
Also 2010-2016, Census API only has percentage of age group. In 2017-2018, it has both whole number and percentage. 

Due to the different variable name, I will gather 2010-2016 and 2017-2018 separately.

In [71]:
# 2010-2016

dic_a = {}
for year in range(2010,2017):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,S0101_C01_023E,S0101_C01_025E,S0101_C01_028E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}/{sub}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic_a[year] = data



2010 556
2011 563
2012 569
2013 583
2014 592
2015 597
2016 606


In [72]:
# For 2017 and 2018
for year in range(2017,2019):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,S0101_C02_024E,S0101_C02_026E,S0101_C02_030E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}/{sub}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic_a[year] = data

2017 615
2018 631


In [73]:
cols_age= ['NAME', 'Per_15to44_years(%)','Per_18_years_and_over(%)','Per_65_years_and_over(%)','Fips_State', 'Fips_Place']

# Set up each year's dataset

cities_2010_a = pd.DataFrame(dic_a[2010][1:], columns=cols_age)
cities_2010_a["Year"]=2010


cities_2011_a = pd.DataFrame(dic_a[2011][1:], columns=cols_age)
cities_2011_a["Year"]=2011


cities_2012_a = pd.DataFrame(dic_a[2012][1:], columns=cols_age)
cities_2012_a["Year"]=2012

cities_2013_a = pd.DataFrame(dic_a[2013][1:], columns=cols_age)
cities_2013_a["Year"]=2013


cities_2014_a = pd.DataFrame(dic_a[2014][1:], columns=cols_age)
cities_2014_a["Year"]=2014


cities_2015_a = pd.DataFrame(dic_a[2015][1:], columns=cols_age)
cities_2015_a["Year"]=2015

cities_2016_a = pd.DataFrame(dic_a[2016][1:], columns=cols_age)
cities_2016_a["Year"]=2016

cities_2017_a = pd.DataFrame(dic_a[2017][1:], columns=cols_age)
cities_2017_a["Year"]=2017

cities_2018_a = pd.DataFrame(dic_a[2018][1:], columns=cols_age)
cities_2018_a["Year"]=2018



print(cities_2010_a.isnull().sum().sum())
print(cities_2011_a.isnull().sum().sum())
print(cities_2012_a.isnull().sum().sum())
print(cities_2013_a.isnull().sum().sum())
print(cities_2014_a.isnull().sum().sum())
print(cities_2015_a.isnull().sum().sum())
print(cities_2016_a.isnull().sum().sum())
print(cities_2017_a.isnull().sum().sum())
print(cities_2018_a.isnull().sum().sum())

0
0
0
0
0
0
0
0
0


#### There are no-value cities.

In [74]:
cities_2010_a.head()

NAME Per_15to44_years(%) Per_18_years_and_over(%)  \
0  Birmingham city, Alabama                42.8                     78.7   
1      Dothan city, Alabama                38.7                     74.8   
2      Hoover city, Alabama                39.7                     71.3   
3  Huntsville city, Alabama                42.5                     78.4   
4      Mobile city, Alabama                40.5                     76.7   

  Per_65_years_and_over(%) Fips_State Fips_Place  Year  
0                     13.1         01      07000  2010  
1                     14.3         01      21184  2010  
2                     12.4         01      35896  2010  
3                     13.5         01      37000  2010  
4                     13.9         01      50000  2010

In [75]:
cities_2018_a.head()

NAME Per_15to44_years(%)  \
0                Yuma city, Arizona                43.1   
1          Concord city, California                41.5   
2  East Los Angeles CDP, California                45.7   
3         El Cajon city, California                45.4   
4             Napa city, California                38.5   

  Per_18_years_and_over(%) Per_65_years_and_over(%) Fips_State Fips_Place  \
0                     74.5                     15.8         04      85540   
1                     83.0                     15.6         06      16000   
2                     75.5                     11.3         06      20802   
3                     74.7                     12.1         06      21712   
4                     77.1                     18.4         06      50258   

   Year  
0  2018  
1  2018  
2  2018  
3  2018  
4  2018

In [76]:

# Combine all age group
frames_a = [cities_2010_a, cities_2011_a, cities_2012_a, cities_2013_a\
            ,cities_2014_a,cities_2015_a,cities_2016_a, cities_2017_a, cities_2018_a]
# Concat all years from 2010-2018
age_result = pd.concat(frames_a)
# Creating columns from fips_state_place for joining the with others
age_result['Fips_State_Place']=age_result['Fips_State']+age_result['Fips_Place']

In [77]:
wave_2_final= pd.merge(wave_2_third , age_result, how='left',on=['Fips_State_Place','Year','NAME','Fips_State', 'Fips_Place'])

In [78]:
wave_2_final.head()

NAME Pop_Total Pop_Male Pop_Female Fips_State  \
0  Birmingham city, Alabama    211670    98760     112910         01   
1      Dothan city, Alabama     66121    31087      35034         01   
2      Hoover city, Alabama     80376    38694      41682         01   
3  Huntsville city, Alabama    181126    88132      92994         01   
4      Mobile city, Alabama    195249    91746     103503         01   

  Fips_Place  Year Fips_State_Place  NYU_500_Largest Pop_White Pop_Black  \
0      07000  2010          0107000                1     47657    158193   
1      21184  2010          0121184                0     41867     21123   
2      35896  2010          0135896                1     57507     11555   
3      37000  2010          0137000                1    114796     53460   
4      50000  2010          0150000                1     89418     98746   

  Pop_Asian Pop_AIAN Pop_NHOPI Pop_Nonhispanic Pop_Hispanic  \
0      1528      593         0          204155         7515   
1       916      186         0           64104         2017   
2      5345      235         0           72254         8122   
3      5734      434       161          170562        10564   
4      2621      474        53          190257         4992   

  Per_15to44_years(%) Per_18_years_and_over(%) Per_65_years_and_over(%)  
0                42.8                     78.7                     13.1  
1                38.7                     74.8                     14.3  
2                39.7                     71.3                     12.4  
3                42.5                     78.4                     13.5  
4                40.5                     76.7                     13.9

In [79]:
wave_2_final.tail()

NAME Pop_Total Pop_Male Pop_Female  \
5298         Menifee city, California     92602    46509      46093   
5299       Riverside city, California    330080   160110     169970   
5300  Springfield city, Massachusetts    155029    75821      79208   
5301          Dale City CDP, Virginia     68805    35840      32965   
5302      South Gate city, California     94439    47917      46522   

     Fips_State Fips_Place  Year Fips_State_Place  NYU_500_Largest Pop_White  \
5298         06      46842  2018          0646842                1     61008   
5299         06      62000  2018          0662000                1    209083   
5300         25      67000  2018          2567000                1     97277   
5301         51      21088  2018          5121088                0     34949   
5302         06      73080  2018          0673080                1     60943   

     Pop_Black Pop_Asian Pop_AIAN Pop_NHOPI Pop_Nonhispanic Pop_Hispanic  \
5298      5099      2617     1302       178           56293        36309   
5299     19591     27672     2736       660          144752       185328   
5300     34369      3681      713         0           80031        74998   
5301     17559      6719      794         0           46928        21877   
5302       611       864      757       653            3503        90936   

     Per_15to44_years(%) Per_18_years_and_over(%) Per_65_years_and_over(%)  
5298                37.1                     74.6                     18.3  
5299                48.7                     76.4                     10.5  
5300                43.6                     75.9                     13.3  
5301                41.7                     72.9                     10.7  
5302                46.0                     71.2                      9.4

In [80]:
wave_2_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5303 entries, 0 to 5302
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   NAME                      5303 non-null   object
 1   Pop_Total                 5298 non-null   object
 2   Pop_Male                  5298 non-null   object
 3   Pop_Female                5298 non-null   object
 4   Fips_State                5303 non-null   object
 5   Fips_Place                5303 non-null   object
 6   Year                      5303 non-null   int64 
 7   Fips_State_Place          5303 non-null   object
 8   NYU_500_Largest           5303 non-null   int64 
 9   Pop_White                 5168 non-null   object
 10  Pop_Black                 5168 non-null   object
 11  Pop_Asian                 5168 non-null   object
 12  Pop_AIAN                  5168 non-null   object
 13  Pop_NHOPI                 5168 non-null   object
 14  Pop_Nonhispanic         

## Treating NONE data

As I checked it before, there are 1 city with Non value in male and female (Villages CDP, Florida) and 135 rows empty from Race. I will mark this value as -998 which is N/A data. 

In [81]:
findnanrows(wave_2_final)

NAME Pop_Total Pop_Male Pop_Female  \
25               Jonesboro city, Arkansas     67486    33384      34102   
83               Lynwood city, California     69863    33415      36448   
182           Boynton Beach city, Florida     68380    31160      37220   
204           Miami Gardens city, Florida    107559    48347      59212   
235                  Meridian city, Idaho     75324    36019      39305   
259                 Fishers town, Indiana     77579    37616      39963   
291           Ellicott City CDP, Maryland     67241    31849      35392   
322                   Troy city, Michigan     81037    40986      40051   
335             Jackson city, Mississippi    173315    79986      93329   
340               O'Fallon city, Missouri     79565    38680      40885   
362          East Orange city, New Jersey     64299    28604      35695   
437   Mount Pleasant town, South Carolina     68112    32790      35322   
439        Rock Hill city, South Carolina     66395    31264      35131   
466              Flower Mound town, Texas     66238    30962      35276   
484                   Mission city, Texas     77586    37526      40060   
490                     Pharr city, Texas     70888    33358      37530   
508                      Sandy city, Utah     87818    44181      43637   
523                Suffolk city, Virginia     84906    41328      43578   
540            Eau Claire city, Wisconsin     65489    31857      33632   
602                     Canton city, Ohio     72925    32834      40091   
638   Mount Pleasant town, South Carolina     69353    34025      35328   
667              Flower Mound town, Texas     67209    33010      34199   
685                   Mission city, Texas     79375    38142      41233   
691                     Pharr city, Texas     72513    34681      37832   
704              Tuscaloosa city, Alabama     91604    40897      50707   
706                Avondale city, Arizona     77526    36926      40600   
718                Surprise city, Arizona    119494    57023      62471   
724              Jonesboro city, Arkansas     68541    33333      35208   
884                  Alafaya CDP, Florida     67743    32867      34876   
892         Deerfield Beach city, Florida     76392    35863      40529   
895              Fort Myers city, Florida     63528    30874      32654   
900                  Kendall CDP, Florida     75893    37609      38284   
903              Lauderhill city, Florida     68115    30798      37317   
908           Miami Gardens city, Florida    109672    50169      59503   
926                  Albany city, Georgia     78701    35386      43315   
931             Johns Creek city, Georgia     79183    39888      39295   
932                   Macon city, Georgia     92138    41234      50904   
939                  Meridian city, Idaho     76742    37434      39308   
947                 Cicero town, Illinois     84263    41212      43051   
988          Lake Charles city, Louisiana     72475    34515      37960   
992                  Portland city, Maine     66368    32259      34109   
995           Ellicott City CDP, Maryland     68010    33751      34259   
1039           Gulfport city, Mississippi     69221    35666      33555   
1045              O'Fallon city, Missouri     80534    40588      39946   
1361                 Meridian city, Idaho     80391    38881      41510   
1362                    Nampa city, Idaho     83932    40145      43787   
1467              O'Fallon city, Missouri     81983    39986      41997   
1606  Mount Pleasant town, South Carolina     71883    32907      38976   
1613             Franklin city, Tennessee     66278    32271      34007   
1614              Jackson city, Tennessee     67263    30579      36684   
1641                Harlingen city, Texas     65688    32617      33071   
1654                  Mission city, Texas     80449    38874      41575   
1660                    Pharr city, Texas     73126    36244  

In [82]:
wave_2_final.fillna("-998",inplace=True)

In [83]:
# ordering columns for dataset

wave_2_final.columns

Index(['NAME', 'Pop_Total', 'Pop_Male', 'Pop_Female', 'Fips_State',
       'Fips_Place', 'Year', 'Fips_State_Place', 'NYU_500_Largest',
       'Pop_White', 'Pop_Black', 'Pop_Asian', 'Pop_AIAN', 'Pop_NHOPI',
       'Pop_Nonhispanic', 'Pop_Hispanic', 'Per_15to44_years(%)',
       'Per_18_years_and_over(%)', 'Per_65_years_and_over(%)'],
      dtype='object')

In [84]:
# Before File extraction, change column type from string to int.

int_col = ['Pop_Total', 'Pop_Male', 'Pop_Female',
       'Pop_White', 'Pop_Black', 'Pop_Asian', 'Pop_AIAN', 'Pop_NHOPI',
       'Pop_Nonhispanic', 'Pop_Hispanic']

for col in int_col :
    wave_2_final[col] = wave_2_final[col].astype(int)
    
    
# Percentage to Float
float_col = ['Per_15to44_years(%)','Per_18_years_and_over(%)', 'Per_65_years_and_over(%)']


for col in float_col:
    wave_2_final[col] = wave_2_final[col].astype(float)

In [85]:
wave_2_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5303 entries, 0 to 5302
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   NAME                      5303 non-null   object 
 1   Pop_Total                 5303 non-null   int64  
 2   Pop_Male                  5303 non-null   int64  
 3   Pop_Female                5303 non-null   int64  
 4   Fips_State                5303 non-null   object 
 5   Fips_Place                5303 non-null   object 
 6   Year                      5303 non-null   int64  
 7   Fips_State_Place          5303 non-null   object 
 8   NYU_500_Largest           5303 non-null   int64  
 9   Pop_White                 5303 non-null   int64  
 10  Pop_Black                 5303 non-null   int64  
 11  Pop_Asian                 5303 non-null   int64  
 12  Pop_AIAN                  5303 non-null   int64  
 13  Pop_NHOPI                 5303 non-null   int64  
 14  Pop_Nonh

In [86]:
# Split NAME into city and state name
wave_2_final[['City_Name','St_Name']]=wave_2_final['NAME'].str.split(",",expand=True)

In [87]:
wave_2_final.head()

NAME  Pop_Total  Pop_Male  Pop_Female Fips_State  \
0  Birmingham city, Alabama     211670     98760      112910         01   
1      Dothan city, Alabama      66121     31087       35034         01   
2      Hoover city, Alabama      80376     38694       41682         01   
3  Huntsville city, Alabama     181126     88132       92994         01   
4      Mobile city, Alabama     195249     91746      103503         01   

  Fips_Place  Year Fips_State_Place  NYU_500_Largest  Pop_White  Pop_Black  \
0      07000  2010          0107000                1      47657     158193   
1      21184  2010          0121184                0      41867      21123   
2      35896  2010          0135896                1      57507      11555   
3      37000  2010          0137000                1     114796      53460   
4      50000  2010          0150000                1      89418      98746   

   Pop_Asian  Pop_AIAN  Pop_NHOPI  Pop_Nonhispanic  Pop_Hispanic  \
0       1528       593          0           204155          7515   
1        916       186          0            64104          2017   
2       5345       235          0            72254          8122   
3       5734       434        161           170562         10564   
4       2621       474         53           190257          4992   

   Per_15to44_years(%)  Per_18_years_and_over(%)  Per_65_years_and_over(%)  \
0                 42.8                      78.7                      13.1   
1                 38.7                      74.8                      14.3   
2                 39.7                      71.3                      12.4   
3                 42.5                      78.4                      13.5   
4                 40.5                      76.7                      13.9   

         City_Name   St_Name  
0  Birmingham city   Alabama  
1      Dothan city   Alabama  
2      Hoover city   Alabama  
3  Huntsville city   Alabama  
4      Mobile city   Alabama

In [88]:
wave_2_final2 = wave_2_final[['Fips_State','Fips_Place','Fips_State_Place','City_Name','St_Name','NYU_500_Largest',\
              'Year','Pop_Total','Per_15to44_years(%)','Per_18_years_and_over(%)', 'Per_65_years_and_over(%)',\
              'Pop_Male', 'Pop_Female', 'Pop_White', 'Pop_Black', 'Pop_Asian', 'Pop_AIAN', 'Pop_NHOPI',\
              'Pop_Nonhispanic', 'Pop_Hispanic']]

In [89]:
wave_2_final2.to_csv(r"/Users/jasonlim/Desktop/EFGS/Census-master/CitiesDataset/Cities_Dataset_Year/Year_2010-2018/place_pop_2010_2018_asrh.csv", index=False, float_format="%.2f")
wave_2_final2.to_excel(r"/Users/jasonlim/Desktop/EFGS/Census-master/CitiesDataset/Cities_Dataset_Year/Year_2010-2018/place_pop_2010_2018_asrh.xlsx", index=False)


# Before 2010

Census Acs1 started from 2005. So, I will pull the oldest ACS1 first and check our variables. <Br>
Yet, ACS1/subject is started from 2010. <br>
    
Therefore, Age group will be calculated by combining of the variables. 
In addition, Ethnicity, we need to use different variables because ACS1 does not have our variables, B03003_003E	B03003_002E until 2009. Therefore, I will test out some variables for that.
    

## Sex and Race

Sex and Race variables are unchanged since the beginning of ACS1. So, I will use these variables to check how many cities are there and establish the initial data frame. 

In [90]:
# Check ACS1 API


dic = {}
for year in range(2005,2010):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,B01001_001E,B01001_002E,B01001_026E,B02001_002E,B02001_003E,B02001_005E,B02001_004E,B02001_006E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'


# Looping over each states

    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic[year] = data
    
    

2005 500
2006 512
2007 521
2008 533
2009 541


In [91]:
cols_sex_race= ['NAME', 'Pop_Total','Pop_Male', 'Pop_Female',\
                'Pop_White', 'Pop_Black', 'Pop_Asian', 'Pop_AIAN', 'Pop_NHOPI',\
                'Fips_State','Fips_Place']

# Set up each year's dataset

cities_2005 = pd.DataFrame(dic[2005][1:], columns=cols_sex_race)
cities_2005["Year"]=2005


cities_2006 = pd.DataFrame(dic[2006][1:], columns=cols_sex_race)
cities_2006["Year"]=2006


cities_2007 = pd.DataFrame(dic[2007][1:], columns=cols_sex_race)
cities_2007["Year"]=2007

cities_2008 = pd.DataFrame(dic[2008][1:], columns=cols_sex_race)
cities_2008["Year"]=2008


cities_2009 = pd.DataFrame(dic[2009][1:], columns=cols_sex_race)
cities_2009["Year"]=2009





In [92]:
print(cities_2005['Pop_Male'].isnull().sum().sum())
print(cities_2006['Pop_Male'].isnull().sum().sum())
print(cities_2007['Pop_Male'].isnull().sum().sum())
print(cities_2008['Pop_Male'].isnull().sum().sum())
print(cities_2009['Pop_Male'].isnull().sum().sum())



print(cities_2005['Pop_White'].isnull().sum().sum())
print(cities_2006['Pop_White'].isnull().sum().sum())
print(cities_2007['Pop_White'].isnull().sum().sum())
print(cities_2008['Pop_White'].isnull().sum().sum())
print(cities_2009['Pop_White'].isnull().sum().sum())

0
0
0
0
0
16
9
8
15
20


**There is no empty rows for sex, but still some empty rows for race**

In [93]:

# Combine all SEX group
frames = [cities_2005, cities_2006,cities_2007,cities_2008,cities_2009]

sex_result_05 = pd.concat(frames)
# Creating columns from fips_state_place for joining the with others
sex_result_05['Fips_State_Place']=sex_result_05['Fips_State']+sex_result_05['Fips_Place']

In [94]:
sex_result_05.head()

NAME Pop_Total Pop_Male Pop_Female Pop_White  \
0  Independence city, Missouri    111842    57505      54337     99498   
1   Kansas City city, Missouri    440885   212392     228493    271210   
2  Lee's Summit city, Missouri     86357    40180      46177     78574   
3      O'Fallon city, Missouri     67875    34618      33257     62989   
4    St. Joseph city, Missouri     68971    32857      36114     64150   

  Pop_Black Pop_Asian Pop_AIAN Pop_NHOPI Fips_State Fips_Place  Year  \
0      4218       689      129        54         29      35000  2005   
1    132187     10878     1988      1054         29      38000  2005   
2      4712       821      268       116         29      41348  2005   
3      3406       682        0         0         29      54074  2005   
4      3038       457      395         0         29      64550  2005   

  Fips_State_Place  
0          2935000  
1          2938000  
2          2941348  
3          2954074  
4          2964550

## Combining with NYU dataset

In [95]:
sex_result_05['NYU_500_Largest'] = sex_result_05['Fips_State_Place'].apply(lambda x:1 if x in nyu_cities else 0)

In [96]:
sex_result_05.head()

NAME Pop_Total Pop_Male Pop_Female Pop_White  \
0  Independence city, Missouri    111842    57505      54337     99498   
1   Kansas City city, Missouri    440885   212392     228493    271210   
2  Lee's Summit city, Missouri     86357    40180      46177     78574   
3      O'Fallon city, Missouri     67875    34618      33257     62989   
4    St. Joseph city, Missouri     68971    32857      36114     64150   

  Pop_Black Pop_Asian Pop_AIAN Pop_NHOPI Fips_State Fips_Place  Year  \
0      4218       689      129        54         29      35000  2005   
1    132187     10878     1988      1054         29      38000  2005   
2      4712       821      268       116         29      41348  2005   
3      3406       682        0         0         29      54074  2005   
4      3038       457      395         0         29      64550  2005   

  Fips_State_Place  NYU_500_Largest  
0          2935000                1  
1          2938000                1  
2          2941348                1  
3          2954074                1  
4          2964550                1

In [97]:
sex_result_05.groupby('Year').sum()

NYU_500_Largest
Year                 
2005              461
2006              467
2007              474
2008              484
2009              487

In [98]:
461/510

0.903921568627451

At the minimum, ACS1 covered 90% of NYU cities, so I will use this.  

## Ethnicity

In 2009, I can use the same variables from Ethnicity. Yet, 2005-2008, variable    B03003_003E	 B03003_002E	are not existed. So, I find out C03001 group from the variables, which are the following variable names. 

Variable|Label|Concept|
--|--|--|
C03001_002E	|Estimate!!Total!!Not Hispanic or Latino	|HISPANIC OR LATINO ORIGIN BY SPECIFIC ORIGIN
C03001_003E	|Estimate!!Total!!Hispanic or Latino	|HISPANIC OR LATINO ORIGIN BY SPECIFIC ORIGIN
  

In [99]:

dic_e_05 = {}
for year in range(2005,2009):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,C03001_002E,C03001_003E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic_e_05[year] = data


2005 500
2006 512
2007 521
2008 533


In [100]:
cols_eth= ['NAME', 'Pop_Nonhispanic', 'Pop_Hispanic','Fips_State', 'Fips_Place']

# Set up each year's dataset



cities_2005_e = pd.DataFrame(dic_e_05[2005][1:], columns=cols_eth)
cities_2005_e["Year"]=2005


cities_2006_e= pd.DataFrame(dic_e_05[2006][1:], columns=cols_eth)
cities_2006_e["Year"]=2006


cities_2007_e = pd.DataFrame(dic_e_05[2007][1:], columns=cols_eth)
cities_2007_e["Year"]=2007

cities_2008_e = pd.DataFrame(dic_e_05[2008][1:], columns=cols_eth)
cities_2008_e["Year"]=2008






print(cities_2005_e.isnull().sum().sum())
print(cities_2006_e.isnull().sum().sum())
print(cities_2007_e.isnull().sum().sum())
print(cities_2008_e.isnull().sum().sum())


390
368
376
374


I still have some missing values. So, I will check B03001 group, which is the first variable for the Race.

In [101]:
dic_e_05_2 = {}
for year in range(2005,2009):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,B03001_002E,B03001_003E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic_e_05_2[year] = data
cols_eth= ['NAME', 'Pop_Nonhispanic', 'Pop_Hispanic','Fips_State', 'Fips_Place']

# Set up each year's dataset



cities_2005_e_2 = pd.DataFrame(dic_e_05_2[2005][1:], columns=cols_eth)
cities_2005_e_2["Year"]=2005


cities_2006_e_2= pd.DataFrame(dic_e_05_2[2006][1:], columns=cols_eth)
cities_2006_e_2["Year"]=2006


cities_2007_e_2 = pd.DataFrame(dic_e_05_2[2007][1:], columns=cols_eth)
cities_2007_e_2["Year"]=2007

cities_2008_e_2 = pd.DataFrame(dic_e_05_2[2008][1:], columns=cols_eth)
cities_2008_e_2["Year"]=2008






print(cities_2005_e_2.isnull().sum().sum())
print(cities_2006_e_2.isnull().sum().sum())
print(cities_2007_e_2.isnull().sum().sum())
print(cities_2008_e_2.isnull().sum().sum())

2005 500
2006 512
2007 521
2008 533
950
964
986
1006


More cities are empty or no-value from B03001 group, so I will keep C03001 for my data.



In [102]:
# for 2009

dic_e_05 = {}
for year in range(2009,2010):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,B03003_002E,B03003_003E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'
    
    
    # Looping over each states
    
    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic_e_05[year] = data


cols_eth= ['NAME', 'Pop_Nonhispanic', 'Pop_Hispanic','Fips_State', 'Fips_Place']

# Set up each year's dataset



cities_2009_e = pd.DataFrame(dic_e_05[2009][1:], columns=cols_eth)
cities_2009_e["Year"]=2009
    
print(cities_2009_e.isnull().sum().sum())
    

2009 541
0


In [103]:

# Combine all SEX group
frames_eth = [cities_2005_e, cities_2006_e,cities_2007_e,cities_2008_e,cities_2009_e]

eth_result_05 = pd.concat(frames_eth)
# Creating columns from fips_state_place for joining the with others
eth_result_05['Fips_State_Place']=eth_result_05['Fips_State']+eth_result_05['Fips_Place']

In [104]:
eth_result_05.head()

NAME Pop_Nonhispanic Pop_Hispanic Fips_State  \
0          Hesperia city, California           46491        33223         06   
1  Huntington Beach city, California          157630        31821         06   
2         Inglewood city, California           51722        68482         06   
3            Irvine city, California          157425        14757         06   
4       Lake Forest city, California           56714        12591         06   

  Fips_Place  Year Fips_State_Place  
0      33434  2005          0633434  
1      36000  2005          0636000  
2      36546  2005          0636546  
3      36770  2005          0636770  
4      39496  2005          0639496

In [105]:
wave_2_05 = pd.merge(sex_result_05 , eth_result_05, how='left',on=['Fips_State_Place','Year','NAME','Fips_State', 'Fips_Place'])

In [106]:
wave_2_05.tail()

NAME Pop_Total Pop_Male Pop_Female  \
2597              St. Charles city, Missouri     65649    33299      32350   
2598             Boynton Beach city, Florida     69643    32782      36861   
2599                 Loveland city, Colorado     66213    30566      35647   
2600  West Bloomfield Township CDP, Michigan     64005    31374      32631   
2601                     Macon city, Georgia     92389    39645      52744   

     Pop_White Pop_Black Pop_Asian Pop_AIAN Pop_NHOPI Fips_State Fips_Place  \
2597      None      None      None     None      None         29      64082   
2598      None      None      None     None      None         12      07875   
2599      None      None      None     None      None         08      46465   
2600      None      None      None     None      None         26      85510   
2601      None      None      None     None      None         13      49000   

      Year Fips_State_Place  NYU_500_Largest Pop_Nonhispanic Pop_Hispanic  
2597  2009          2964082                0           64050         1599  
2598  2009          1207875                1           61495         8148  
2599  2009          0846465                1           57294         8919  
2600  2009          2685510                0           63116          889  
2601  2009          1349000                1           91140         1249

## Age Group 2005-2009

Since there is no ACS1/subject table, Age group will be calculated by combining the age and sex variables from ACS1.

This is the chart for how I made the calculation for Age group

Year | 15 to 44 years | 18 years and over | 65 years and over
-- | -- | -- | --
Formula | Sum of all variables between 15-44 years | Total population - (under 18 years male and   female)|Sum of all variables after 65 years|
2005 | B01001_006E, B01001_007E, B01001_008E, B01001_009E, B01001_010E,   B01001_011E, B01001_012E, B01001_013E, B01001_014E, B01001_030E, B01001_031E, B01001_032E, B01001_033E, B01001_034E, B01001_035E, B01001_036E, B01001_037E,   B01001_038E | B01001_001E   -sum(B01001_003E, B01001_004E, B01001_005E, B01001_006E, B01001_027E,   B01001_028E, B01001_029E, B01001_030E) | B01001_020E,     B01001_021E,     B01001_022E,     B01001_023E,     B01001_024E,     B01001_025E, B01001_044E,     B01001_045E,     B01001_046E,     B01001_047E,     B01001_048E,     B01001_049E



After combining the whole number, I will convert into percentage since 2010-2018, we have percentage for the age group. So, it will give us constant format of numbers.

In [107]:
# Check ACS1 API


dic_a_05 = {}
for year in range(2005,2010):
    dsource='acs'

    dname='acs1'
    sub = 'subject'
    cols='NAME,B01001_001E,B01001_006E,B01001_007E,B01001_008E,B01001_009E,B01001_010E,B01001_011E,B01001_012E,B01001_013E,B01001_014E,B01001_030E,B01001_031E,B01001_032E,B01001_033E,B01001_034E,B01001_035E,B01001_036E,B01001_037E,B01001_038E,B01001_003E,B01001_004E,B01001_005E,B01001_027E,B01001_028E,B01001_029E,B01001_020E,B01001_021E,B01001_022E,B01001_023E,B01001_024E,B01001_025E,B01001_044E,B01001_045E,B01001_046E,B01001_047E,B01001_048E,B01001_049E'
    base_url = f'https://api.census.gov/data/{year}/{dsource}/{dname}?get={cols}'


# Looping over each states

    data_url= f'{base_url}&for=place:*&in=state:*&key={api_key}'
    #print(data_url)
    response = requests.get(data_url)
    data=response.json()
    # Check how many place code in the each API
    print(year, len(data))
    dic_a_05[year] = data
    
    

2005 500
2006 512
2007 521
2008 533
2009 541


In [108]:
cols_age_05= ['NAME', 'Pop_Total','Male!!15 to 17 years','Male!!18 and 19 years',\
                'Male!!20 years','Male!!21 years','Male!!22 to 24 years','Male!!25 to 29 years',\
                'Male!!30 to 34 years','Male!!35 to 39 years','Male!!40 to 44 years',\
                'Female!!15 to 17 years','Female!!18 and 19 years','Female!!20 years','Female!!21 years',\
                'Female!!22 to 24 years','Female!!25 to 29 years','Female!!30 to 34 years',\
                'Female!!35 to 39 years','Female!!40 to 44 years','Male!!Under 5 years','Male!!5 to 9 years',\
                'Male!!10 to 14 years','Female!!Under 5 years','Female!!5 to 9 years','Female!!10 to 14 years',\
                'Male!!65 and 66 years','Male!!67 to 69 years','Male!!70 to 74 years','Male!!75 to 79 years',\
                'Male!!80 to 84 years','Male!!85 years and over','Female!!65 and 66 years','Female!!67 to 69 years',\
                'Female!!70 to 74 years','Female!!75 to 79 years','Female!!80 to 84 years','Female!!85 years and over',\
                'Fips_State', 'Fips_Place']

# Set up each year's dataset

cities_2005_a_05 = pd.DataFrame(dic_a_05[2005][1:], columns=cols_age_05)
cities_2005_a_05["Year"]=2005


cities_2006_a_05 = pd.DataFrame(dic_a_05[2006][1:], columns=cols_age_05)
cities_2006_a_05["Year"]=2006


cities_2007_a_05 = pd.DataFrame(dic_a_05[2007][1:], columns=cols_age_05)
cities_2007_a_05["Year"]=2007

cities_2008_a_05 = pd.DataFrame(dic_a_05[2008][1:], columns=cols_age_05)
cities_2008_a_05["Year"]=2008


cities_2009_a_05 = pd.DataFrame(dic_a_05[2009][1:], columns=cols_age_05)
cities_2009_a_05["Year"]=2009


print(cities_2005_a_05.isnull().sum().sum())
print(cities_2006_a_05.isnull().sum().sum())
print(cities_2007_a_05.isnull().sum().sum())
print(cities_2008_a_05.isnull().sum().sum())
print(cities_2009_a_05.isnull().sum().sum())

0
0
0
0
0


**There are no empty rows.**

I want to combine all years and perform my calculation for my age group

In [109]:

# Combine all SEX group
frames_age_05 = [cities_2005_a_05, cities_2006_a_05,cities_2007_a_05,cities_2008_a_05,cities_2009_a_05]

age_result_05 = pd.concat(frames_age_05)
# Creating columns from fips_state_place for joining the with others
age_result_05['Fips_State_Place']=age_result_05['Fips_State']+age_result_05['Fips_Place']

In [110]:
age_result_05.head()

NAME Pop_Total Male!!15 to 17 years  \
0  Birmingham city, Alabama    222154                 4643   
1      Hoover city, Alabama     74473                 1160   
2  Huntsville city, Alabama    158618                 3207   
3      Mobile city, Alabama    193332                 4211   
4  Montgomery city, Alabama    193042                 3765   

  Male!!18 and 19 years Male!!20 years Male!!21 years Male!!22 to 24 years  \
0                  3188           2222           1370                 5172   
1                   978              0             62                 1754   
2                  1917            805            790                 4400   
3                  2537           1592           1269                 3589   
4                  2577            660           2306                 3412   

  Male!!25 to 29 years Male!!30 to 34 years Male!!35 to 39 years  \
0                 7418                 7524                 6840   
1                 2751                 2607                 2639   
2                 5281                 4835                 4462   
3                 6801                 5938                 5257   
4                 5681                 5861                 6799   

  Male!!40 to 44 years Female!!15 to 17 years Female!!18 and 19 years  \
0                 7642                   4597                    4057   
1                 2452                   1254                     686   
2                 7529                   3794                    1842   
3                 5961                   4022                    2536   
4                 5580                   4429                    2222   

  Female!!20 years Female!!21 years Female!!22 to 24 years  \
0             1047             2746                   4333   
1              264              291                   1063   
2             1755              834                   4209   
3             1511             1933                   4250   
4             1390             2376                   3985   

  Female!!25 to 29 years Female!!30 to 34 years Female!!35 to 39 years  \
0                   8366                   8903                   7863   
1                   3737                   2596                   3066   
2                   5480                   5028                   4459   
3                   8110                   6486                   7024   
4                   6638                   6502                   7284   

  Female!!40 to 44 years Male!!Under 5 years Male!!5 to 9 years  \
0                   8854                9507               6902   
1                   2831                2929               2022   
2                   7853                4794               4733   
3                   7042                7121               7348   
4                   7513                7655               7560   

  Male!!10 to 14 years Female!!Under 5 years Female!!5 to 9 years  \
0                 9621                  7915                 6632   
1                 2488                  3071                 2249   
2                 6480                  4521                 3070   
3                 6510                  7359                 7392   
4                 6740                  7546                 7547   

  Female!!10 to 14 years Male!!65 and 66 years Male!!67 to 69 years  \
0                   7782                  1266                 1465   
1                   3028                   394                  555   
2                   4758                  1280                 2156   
3                   6728                  1052                 2348   
4                   6830                  2333                  996   

  Male!!70 to 74 years Male!!75 to 79 years Male!!80 to 84 years  \
0                 2639                 1467                 1141   
1                 1215                  641                  290   
2                 3860                 1529                 1208  

In [111]:
age_result_05.columns

Index(['NAME', 'Pop_Total', 'Male!!15 to 17 years', 'Male!!18 and 19 years',
       'Male!!20 years', 'Male!!21 years', 'Male!!22 to 24 years',
       'Male!!25 to 29 years', 'Male!!30 to 34 years', 'Male!!35 to 39 years',
       'Male!!40 to 44 years', 'Female!!15 to 17 years',
       'Female!!18 and 19 years', 'Female!!20 years', 'Female!!21 years',
       'Female!!22 to 24 years', 'Female!!25 to 29 years',
       'Female!!30 to 34 years', 'Female!!35 to 39 years',
       'Female!!40 to 44 years', 'Male!!Under 5 years', 'Male!!5 to 9 years',
       'Male!!10 to 14 years', 'Female!!Under 5 years', 'Female!!5 to 9 years',
       'Female!!10 to 14 years', 'Male!!65 and 66 years',
       'Male!!67 to 69 years', 'Male!!70 to 74 years', 'Male!!75 to 79 years',
       'Male!!80 to 84 years', 'Male!!85 years and over',
       'Female!!65 and 66 years', 'Female!!67 to 69 years',
       'Female!!70 to 74 years', 'Female!!75 to 79 years',
       'Female!!80 to 84 years', 'Female!!85 years and o

In [112]:
# Check Column type
age_result_05.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2602 entries, 0 to 539
Data columns (total 42 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   NAME                       2602 non-null   object
 1   Pop_Total                  2602 non-null   object
 2   Male!!15 to 17 years       2602 non-null   object
 3   Male!!18 and 19 years      2602 non-null   object
 4   Male!!20 years             2602 non-null   object
 5   Male!!21 years             2602 non-null   object
 6   Male!!22 to 24 years       2602 non-null   object
 7   Male!!25 to 29 years       2602 non-null   object
 8   Male!!30 to 34 years       2602 non-null   object
 9   Male!!35 to 39 years       2602 non-null   object
 10  Male!!40 to 44 years       2602 non-null   object
 11  Female!!15 to 17 years     2602 non-null   object
 12  Female!!18 and 19 years    2602 non-null   object
 13  Female!!20 years           2602 non-null   object
 14  Female!!2

In [113]:
# Before Calculation, change column type from string to int.
age_int_col = ['Pop_Total', 'Male!!15 to 17 years',
       'Male!!18 and 19 years', 'Male!!20 years', 'Male!!21 years',
       'Male!!22 to 24 years', 'Male!!25 to 29 years', 'Male!!30 to 34 years',
       'Male!!35 to 39 years', 'Male!!40 to 44 years',
       'Female!!15 to 17 years', 'Female!!18 and 19 years', 'Female!!20 years',
       'Female!!21 years', 'Female!!22 to 24 years', 'Female!!25 to 29 years',
       'Female!!30 to 34 years', 'Female!!35 to 39 years',
       'Female!!40 to 44 years', 'Male!!Under 5 years', 'Male!!5 to 9 years',
       'Male!!10 to 14 years','Female!!Under 5 years', 'Female!!5 to 9 years',
       'Female!!10 to 14 years', 
       'Male!!65 and 66 years', 'Male!!67 to 69 years', 'Male!!70 to 74 years',
       'Male!!75 to 79 years', 'Male!!80 to 84 years',
       'Male!!85 years and over', 'Female!!65 and 66 years',
       'Female!!67 to 69 years', 'Female!!70 to 74 years',
       'Female!!75 to 79 years', 'Female!!80 to 84 years',
       'Female!!85 years and over']


for col in age_int_col:
    age_result_05[col]=age_result_05[col].astype(int)

In [114]:
age_result_05.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2602 entries, 0 to 539
Data columns (total 42 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   NAME                       2602 non-null   object
 1   Pop_Total                  2602 non-null   int64 
 2   Male!!15 to 17 years       2602 non-null   int64 
 3   Male!!18 and 19 years      2602 non-null   int64 
 4   Male!!20 years             2602 non-null   int64 
 5   Male!!21 years             2602 non-null   int64 
 6   Male!!22 to 24 years       2602 non-null   int64 
 7   Male!!25 to 29 years       2602 non-null   int64 
 8   Male!!30 to 34 years       2602 non-null   int64 
 9   Male!!35 to 39 years       2602 non-null   int64 
 10  Male!!40 to 44 years       2602 non-null   int64 
 11  Female!!15 to 17 years     2602 non-null   int64 
 12  Female!!18 and 19 years    2602 non-null   int64 
 13  Female!!20 years           2602 non-null   int64 
 14  Female!!2

In [115]:
age_result_05.reset_index(inplace=True,drop=True)

In [116]:
age_result_05.tail()

NAME  Pop_Total  Male!!15 to 17 years  \
2597  Guaynabo zona urbana, Puerto Rico      83339                  1965   
2598     Ponce zona urbana, Puerto Rico     145399                  3291   
2599  San Juan zona urbana, Puerto Rico     406603                  8371   
2600  Mayagüez zona urbana, Puerto Rico      74154                  1664   
2601   Bayamón zona urbana, Puerto Rico     195815                  4293   

      Male!!18 and 19 years  Male!!20 years  Male!!21 years  \
2597                   1163             475             516   
2598                   2397             902            1164   
2599                   5550            4223            2461   
2600                   1363             941             606   
2601                   2904            1414            1567   

      Male!!22 to 24 years  Male!!25 to 29 years  Male!!30 to 34 years  \
2597                  1838                  2593                  1969   
2598                  3267                  4188                  4690   
2599                  6478                 13994                 14035   
2600                  1932                  3125                  2363   
2601                  4112                  7128                  5889   

      Male!!35 to 39 years  Male!!40 to 44 years  Female!!15 to 17 years  \
2597                  2675                  2864                    1706   
2598                  4284                  4026                    3618   
2599                 13935                 11547                    8327   
2600                  1973                  1925                    1405   
2601                  5940                  6491                    4398   

      Female!!18 and 19 years  Female!!20 years  Female!!21 years  \
2597                     1308               597               348   
2598                     2099              1393              1034   
2599                     5581              2407              3799   
2600                     1327              1155               570   
2601                     2805              1814              1135   

      Female!!22 to 24 years  Female!!25 to 29 years  Female!!30 to 34 years  \
2597                    1754                    2585                    2644   
2598                    2723                    5136                    5084   
2599                    7775                   15425                   14963   
2600                    1525                    3018                    2401   
2601                    3768                    6261                    6657   

      Female!!35 to 39 years  Female!!40 to 44 years  Male!!Under 5 years  \
2597                    2531                    3608                 2631   
2598                    3998                    5012                 4513   
2599                   12622                   14305                11366   
2600                    1823                    2301                 2247   
2601                    5449                    7333                 5715   

      Male!!5 to 9 years  Male!!10 to 14 years  Female!!Under 5 years  \
2597                2603                  2384                   1949   
2598                5606                  5300                   3917   
2599               12682                 12820                  10881   
2600                1741                  2708                   2036   
2601                5779                  7274                   4970   

      Female!!5 to 9 years  Female!!10 to 14 years  Male!!65 and 66 years  \
2597                  1959                    3330                    694   
2598                  4595                    5270                   1053   
2599                 10868                   12931                   3247   
2600                  2260                    2234                    498   
2601                  5331                    7324                   1933   

      Male!!67 to 69 years  Male!!70

In [117]:
age_result_05["Female!!15 to 17 years"].head()

0    4597
1    1254
2    3794
3    4022
4    4429
Name: Female!!15 to 17 years, dtype: int64

In [118]:
# Calculation for 15-44 years.
age_result_05['Per_15to44_years(%)'] = 100*round((age_result_05['Male!!15 to 17 years']+age_result_05['Male!!18 and 19 years']\
                                             +age_result_05['Male!!20 years']+age_result_05['Male!!21 years']\
                                             +age_result_05['Male!!22 to 24 years']+age_result_05['Male!!25 to 29 years']\
                                             +age_result_05['Male!!30 to 34 years']+age_result_05['Male!!35 to 39 years']\
                                             +age_result_05['Male!!40 to 44 years']+age_result_05['Female!!15 to 17 years']\
                                             +age_result_05['Female!!18 and 19 years']+age_result_05['Female!!20 years']\
                                             +age_result_05['Female!!21 years']+age_result_05['Female!!22 to 24 years']\
                                             +age_result_05['Female!!25 to 29 years']+age_result_05['Female!!30 to 34 years']\
                                             +age_result_05['Female!!35 to 39 years']+age_result_05['Female!!40 to 44 years'])\
                                            /age_result_05['Pop_Total'],4)


In [119]:
# Calculation for 18 years and over

age_result_05['Per_18_years_and_over(%)'] = 100*round((age_result_05['Pop_Total']-(age_result_05['Male!!Under 5 years']\
                                                                            +age_result_05['Male!!5 to 9 years']\
                                                                            +age_result_05['Male!!10 to 14 years']\
                                                                            +age_result_05['Male!!15 to 17 years']\
                                                                            +age_result_05['Female!!Under 5 years']\
                                                                            +age_result_05['Female!!5 to 9 years']\
                                                                            +age_result_05['Female!!10 to 14 years']\
                                                                            +age_result_05['Female!!15 to 17 years']))\
                                               /age_result_05['Pop_Total'],4)

In [120]:
# calculation for 65 years and over

age_result_05['Per_65_years_and_over(%)'] = 100*round((age_result_05['Male!!65 and 66 years']+age_result_05['Male!!67 to 69 years']\
                                                +age_result_05['Male!!70 to 74 years']+age_result_05['Male!!75 to 79 years']\
                                                +age_result_05['Male!!80 to 84 years']+age_result_05['Male!!85 years and over']\
                                                +age_result_05['Female!!65 and 66 years']+age_result_05['Female!!67 to 69 years']\
                                                +age_result_05['Female!!70 to 74 years']+age_result_05['Female!!75 to 79 years']\
                                                +age_result_05['Female!!80 to 84 years']+age_result_05['Female!!85 years and over'])\
                                               /age_result_05['Pop_Total'],4)

In [121]:

age_result_05.head()

NAME  Pop_Total  Male!!15 to 17 years  \
0  Birmingham city, Alabama     222154                  4643   
1      Hoover city, Alabama      74473                  1160   
2  Huntsville city, Alabama     158618                  3207   
3      Mobile city, Alabama     193332                  4211   
4  Montgomery city, Alabama     193042                  3765   

   Male!!18 and 19 years  Male!!20 years  Male!!21 years  \
0                   3188            2222            1370   
1                    978               0              62   
2                   1917             805             790   
3                   2537            1592            1269   
4                   2577             660            2306   

   Male!!22 to 24 years  Male!!25 to 29 years  Male!!30 to 34 years  \
0                  5172                  7418                  7524   
1                  1754                  2751                  2607   
2                  4400                  5281                  4835   
3                  3589                  6801                  5938   
4                  3412                  5681                  5861   

   Male!!35 to 39 years  Male!!40 to 44 years  Female!!15 to 17 years  \
0                  6840                  7642                    4597   
1                  2639                  2452                    1254   
2                  4462                  7529                    3794   
3                  5257                  5961                    4022   
4                  6799                  5580                    4429   

   Female!!18 and 19 years  Female!!20 years  Female!!21 years  \
0                     4057              1047              2746   
1                      686               264               291   
2                     1842              1755               834   
3                     2536              1511              1933   
4                     2222              1390              2376   

   Female!!22 to 24 years  Female!!25 to 29 years  Female!!30 to 34 years  \
0                    4333                    8366                    8903   
1                    1063                    3737                    2596   
2                    4209                    5480                    5028   
3                    4250                    8110                    6486   
4                    3985                    6638                    6502   

   Female!!35 to 39 years  Female!!40 to 44 years  Male!!Under 5 years  \
0                    7863                    8854                 9507   
1                    3066                    2831                 2929   
2                    4459                    7853                 4794   
3                    7024                    7042                 7121   
4                    7284                    7513                 7655   

   Male!!5 to 9 years  Male!!10 to 14 years  Female!!Under 5 years  \
0                6902                  9621                   7915   
1                2022                  2488                   3071   
2                4733                  6480                   4521   
3                7348                  6510                   7359   
4                7560                  6740                   7546   

   Female!!5 to 9 years  Female!!10 to 14 years  Male!!65 and 66 years  \
0                  6632                    7782                   1266   
1                  2249                    3028                    394   
2                  3070                    4758                   1280   
3                  7392                    6728                   1052   
4                  7547                    6830                   2333   

   Male!!67 to 69 years  Male!!70 to 74 years  Male!!75 to 79 years  \
0                  1465                  2639                  1467   
1                   555                  1215                   641   
2                  2156    

In [122]:
age_result_05.columns

Index(['NAME', 'Pop_Total', 'Male!!15 to 17 years', 'Male!!18 and 19 years',
       'Male!!20 years', 'Male!!21 years', 'Male!!22 to 24 years',
       'Male!!25 to 29 years', 'Male!!30 to 34 years', 'Male!!35 to 39 years',
       'Male!!40 to 44 years', 'Female!!15 to 17 years',
       'Female!!18 and 19 years', 'Female!!20 years', 'Female!!21 years',
       'Female!!22 to 24 years', 'Female!!25 to 29 years',
       'Female!!30 to 34 years', 'Female!!35 to 39 years',
       'Female!!40 to 44 years', 'Male!!Under 5 years', 'Male!!5 to 9 years',
       'Male!!10 to 14 years', 'Female!!Under 5 years', 'Female!!5 to 9 years',
       'Female!!10 to 14 years', 'Male!!65 and 66 years',
       'Male!!67 to 69 years', 'Male!!70 to 74 years', 'Male!!75 to 79 years',
       'Male!!80 to 84 years', 'Male!!85 years and over',
       'Female!!65 and 66 years', 'Female!!67 to 69 years',
       'Female!!70 to 74 years', 'Female!!75 to 79 years',
       'Female!!80 to 84 years', 'Female!!85 years and o

In [123]:
# Filter only the necessary columns
age_final_05 = age_result_05[['NAME','Per_15to44_years(%)','Per_18_years_and_over(%)', \
                              'Per_65_years_and_over(%)','Fips_State',\
                              'Fips_Place', 'Year', 'Fips_State_Place' ]]

In [124]:
age_final_05.head()

NAME  Per_15to44_years(%)  Per_18_years_and_over(%)  \
0  Birmingham city, Alabama                43.57                     74.07   
1      Hoover city, Alabama                40.54                     75.56   
2  Huntsville city, Alabama                43.17                     77.71   
3      Mobile city, Alabama                41.42                     73.78   
4  Montgomery city, Alabama                40.91                     73.03   

   Per_65_years_and_over(%) Fips_State Fips_Place  Year Fips_State_Place  
0                     11.65         01      07000  2005          0107000  
1                     10.98         01      35896  2005          0135896  
2                     14.70         01      37000  2005          0137000  
3                     13.53         01      50000  2005          0150000  
4                     11.55         01      51000  2005          0151000

In [125]:
wave_2_final_05= pd.merge(wave_2_05 , age_final_05, how='left',on=['Fips_State_Place','Year','NAME','Fips_State', 'Fips_Place'])

In [126]:
wave_2_final_05.head()

NAME Pop_Total Pop_Male Pop_Female Pop_White  \
0  Independence city, Missouri    111842    57505      54337     99498   
1   Kansas City city, Missouri    440885   212392     228493    271210   
2  Lee's Summit city, Missouri     86357    40180      46177     78574   
3      O'Fallon city, Missouri     67875    34618      33257     62989   
4    St. Joseph city, Missouri     68971    32857      36114     64150   

  Pop_Black Pop_Asian Pop_AIAN Pop_NHOPI Fips_State Fips_Place  Year  \
0      4218       689      129        54         29      35000  2005   
1    132187     10878     1988      1054         29      38000  2005   
2      4712       821      268       116         29      41348  2005   
3      3406       682        0         0         29      54074  2005   
4      3038       457      395         0         29      64550  2005   

  Fips_State_Place  NYU_500_Largest Pop_Nonhispanic Pop_Hispanic  \
0          2935000                1            None         None   
1          2938000                1          404890        35995   
2          2941348                1            None         None   
3          2954074                1            None         None   
4          2964550                1            None         None   

   Per_15to44_years(%)  Per_18_years_and_over(%)  Per_65_years_and_over(%)  
0                39.20                     77.45                     14.87  
1                44.74                     75.39                     10.56  
2                39.48                     69.75                     10.24  
3                46.09                     69.50                      6.16  
4                42.88                     75.05                     13.79

In [127]:
wave_2_final_05.tail()

NAME Pop_Total Pop_Male Pop_Female  \
2597              St. Charles city, Missouri     65649    33299      32350   
2598             Boynton Beach city, Florida     69643    32782      36861   
2599                 Loveland city, Colorado     66213    30566      35647   
2600  West Bloomfield Township CDP, Michigan     64005    31374      32631   
2601                     Macon city, Georgia     92389    39645      52744   

     Pop_White Pop_Black Pop_Asian Pop_AIAN Pop_NHOPI Fips_State Fips_Place  \
2597      None      None      None     None      None         29      64082   
2598      None      None      None     None      None         12      07875   
2599      None      None      None     None      None         08      46465   
2600      None      None      None     None      None         26      85510   
2601      None      None      None     None      None         13      49000   

      Year Fips_State_Place  NYU_500_Largest Pop_Nonhispanic Pop_Hispanic  \
2597  2009          2964082                0           64050         1599   
2598  2009          1207875                1           61495         8148   
2599  2009          0846465                1           57294         8919   
2600  2009          2685510                0           63116          889   
2601  2009          1349000                1           91140         1249   

      Per_15to44_years(%)  Per_18_years_and_over(%)  Per_65_years_and_over(%)  
2597                39.00                     79.46                     16.75  
2598                36.36                     81.54                     23.53  
2599                40.56                     76.14                     14.59  
2600                34.66                     78.13                     13.50  
2601                42.31                     74.54                     12.97

## Treating NONE data and change column type to integer and float for population and percentage columns.
 I will mark this value as -998 which is N/A data. 

In [128]:
# fill none value with -998
wave_2_final_05.fillna("-998",inplace=True)

In [129]:
# Before Calculation, change column type from string to int.

int_col = ['Pop_Total', 'Pop_Male', 'Pop_Female',
       'Pop_White', 'Pop_Black', 'Pop_Asian', 'Pop_AIAN', 'Pop_NHOPI',
       'Pop_Nonhispanic', 'Pop_Hispanic']

for col in int_col :
    wave_2_final_05[col] = wave_2_final_05[col].astype(int)
    
    
# Percentage to Float
float_col = ['Per_15to44_years(%)','Per_18_years_and_over(%)', 'Per_65_years_and_over(%)']


for col in float_col:
    wave_2_final_05[col] = wave_2_final_05[col].astype(float)

In [130]:
# Split NAME into city and state name
wave_2_final_05[['City_Name','St_Name']]=wave_2_final_05['NAME'].str.split(",",expand=True)

In [131]:
wave_2_final_05.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2602 entries, 0 to 2601
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   NAME                      2602 non-null   object 
 1   Pop_Total                 2602 non-null   int64  
 2   Pop_Male                  2602 non-null   int64  
 3   Pop_Female                2602 non-null   int64  
 4   Pop_White                 2602 non-null   int64  
 5   Pop_Black                 2602 non-null   int64  
 6   Pop_Asian                 2602 non-null   int64  
 7   Pop_AIAN                  2602 non-null   int64  
 8   Pop_NHOPI                 2602 non-null   int64  
 9   Fips_State                2602 non-null   object 
 10  Fips_Place                2602 non-null   object 
 11  Year                      2602 non-null   int64  
 12  Fips_State_Place          2602 non-null   object 
 13  NYU_500_Largest           2602 non-null   int64  
 14  Pop_Nonh

#### Create Dataframe to CSV and Excel File

In [132]:

# Re-order the dataset
wave_2_final_05_a = wave_2_final_05[['Fips_State','Fips_Place','Fips_State_Place','City_Name','St_Name','NYU_500_Largest',\
              'Year','Pop_Total','Per_15to44_years(%)','Per_18_years_and_over(%)', 'Per_65_years_and_over(%)',\
              'Pop_Male', 'Pop_Female', 'Pop_White', 'Pop_Black', 'Pop_Asian', 'Pop_AIAN', 'Pop_NHOPI',\
              'Pop_Nonhispanic', 'Pop_Hispanic']]

wave_2_final_05_a.to_csv(r"/Users/jasonlim/Desktop/EFGS/Census-master/CitiesDataset/Cities_Dataset_Year/Year_2005-2009/place_pop_2005_2009_asrh.csv", \
                         index=False, float_format="%.2f")
wave_2_final_05_a.to_excel(r"/Users/jasonlim/Desktop/EFGS/Census-master/CitiesDataset/Cities_Dataset_Year/Year_2005-2009/place_pop_2005_2009_asrh.xlsx", \
                           index=False, float_format="%.2f")


In [133]:
# Combine All ACS1 dataframe

wave_2005_2018 = pd.concat([wave_2_final_05_a,wave_2_final2])

In [134]:
wave_2005_2018.head()

Fips_State Fips_Place Fips_State_Place          City_Name    St_Name  \
0         29      35000          2935000  Independence city   Missouri   
1         29      38000          2938000   Kansas City city   Missouri   
2         29      41348          2941348  Lee's Summit city   Missouri   
3         29      54074          2954074      O'Fallon city   Missouri   
4         29      64550          2964550    St. Joseph city   Missouri   

   NYU_500_Largest  Year  Pop_Total  Per_15to44_years(%)  \
0                1  2005     111842                39.20   
1                1  2005     440885                44.74   
2                1  2005      86357                39.48   
3                1  2005      67875                46.09   
4                1  2005      68971                42.88   

   Per_18_years_and_over(%)  Per_65_years_and_over(%)  Pop_Male  Pop_Female  \
0                     77.45                     14.87     57505       54337   
1                     75.39                     10.56    212392      228493   
2                     69.75                     10.24     40180       46177   
3                     69.50                      6.16     34618       33257   
4                     75.05                     13.79     32857       36114   

   Pop_White  Pop_Black  Pop_Asian  Pop_AIAN  Pop_NHOPI  Pop_Nonhispanic  \
0      99498       4218        689       129         54             -998   
1     271210     132187      10878      1988       1054           404890   
2      78574       4712        821       268        116             -998   
3      62989       3406        682         0          0             -998   
4      64150       3038        457       395          0             -998   

   Pop_Hispanic  
0          -998  
1         35995  
2          -998  
3          -998  
4          -998

In [135]:
# These files are just for combining. It will be removed once all-year combined is set up
wave_2005_2018.to_csv("place_pop_2005_2018_asrh.csv", index=False,float_format="%.2f")
